In [1]:
import os

from dataset_wo_config_files import  Mention, CDCR_Dataset

In [2]:
ecb_paths = ['../CDCR/data/ECBplus-prep/output_data/train']
cdcr_test = CDCR_Dataset(name="cdcr_test", data_path=ecb_paths,context_method="hsu")

In [10]:
import random
index_r=random.randint(0,1000)
mention_idsss= list(cdcr_test.mentions.keys())[index_r]
mention = cdcr_test.mentions[mention_idsss]
print(mention.sent_id)
print(mention.tokens_number)
print(mention.tokens_str)
print(mention.new_context)

3
[0, 1]
Lindsay Lohan
(['http', ':', '/', '/', 'music', '.', 'yahoo', '.', 'com', '/', 'news', '/', 'lawyer', '-', 'lindsay', '-', 'lohan', '-', 'checks', '-', 'rehab', '-', 'facility', '-', '162019483', '.', 'html', 'Lawyer', ':', 'Lindsay', 'Lohan', 'checks', 'into', 'rehab', 'facility'], ['[E]', 'Lindsay', 'Lohan', '[/E]', 'has', 'checked', 'into', 'a', 'rehab', 'facility', 'to', 'comply', 'with', 'her', 'sentence', 'in', 'a', 'misdemeanor', 'driving', 'case', ',', 'but', 'her', 'arrival', 'there', 'was', 'not', 'without', 'drama', '.'])

In [14]:
cdcr_test.mentions_by_topics["33"]

['33_1ecb_UNK82YrqPFfuqLZtEPMr_1_2_H6Pz',
 '33_1ecb_UNK82YrqPFfuqLZtEPMr_6_3_7tj4',
 '33_2ecb_UNK82YrqPFfuqLZtEPMr_0_23_hJuR',
 '33_2ecb_UNK82YrqPFfuqLZtEPMr_0_19_CJfU',
 '33_2ecb_UNK82YrqPFfuqLZtEPMr_7_4_S4Ja',
 '33_2ecb_UNK82YrqPFfuqLZtEPMr_7_11_hFAH',
 '33_3ecb_UNK82YrqPFfuqLZtEPMr_0_11_e3DJ',
 '33_3ecb_UNK82YrqPFfuqLZtEPMr_0_2_TyT5',
 '33_3ecb_UNK82YrqPFfuqLZtEPMr_0_26_mChF',
 '33_3ecb_UNK82YrqPFfuqLZtEPMr_5_7_BKyN',
 '33_3ecb_UNK82YrqPFfuqLZtEPMr_4_13_6h6k',
 '33_5ecb_UNK82YrqPFfuqLZtEPMr_2_2_FPtv',
 '33_1ecb_NON27398791555720446_0_10_5FG3',
 '33_1ecb_NON27398791555720446_6_34_JKiF',
 '33_1ecb_NON27398791555720446_2_21_UAFt',
 '33_3ecb_NON27398791555720446_5_4_nNE6',
 '33_4ecb_NON27398791555720446_1_30_eKzM',
 '33_4ecb_NON27398791555720446_1_37_6Dau',
 '33_5ecb_NON27398791555720446_0_4_WeJd',
 '33_5ecb_NON27398791555720446_2_15_hdpc',
 '33_1ecb_HUM27398765576549920_0_1_5vuo',
 '33_1ecb_HUM27398765576549920_0_29_nHzn',
 '33_1ecb_HUM27398765576549920_0_31_QBia',
 '33_3ecb_HUM27398765576549920_46_10_m4MW',
 '33_1ecb_LOC17633735788671631_0_11_Cy6F',
 '33_1ecb_LOC17633735788671631_6_14_4NUa',
 '33_5ecb_LOC17633735788671631_19_14_JZiu',
 '33_5ecb_LOC17633735788671631_0_19_EXXR',
 '33_1ecb_HUM17586020069902806_0_33_Puq5',
 '33_1ecb_HUM17586020069902806_1_12_SqMi',
 '33_1ecb_HUM17586020069902806_0_25_Dpo2',
 '33_1ecb_HUM17586020069902806_0_5_hs8g',
 '33_2ecb_HUM17586020069902806_0_16_RfFT',
 '33_3ecb_HUM17586020069902806_49_1_VBSo',
 '33_3ecb_HUM17586020069902806_46_14_amJp',
 '33_3ecb_HUM17586020069902806_47_2_bSKC',
 '33_3ecb_HUM17586020069902806_46_5_cURh',
 '33_3ecb_HUM17586020069902806_46_1_Zbi9',
 '33_3ecb_HUM17586020069902806_0_18_8kCF',
 '33_4ecb_HUM17586020069902806_0_26_ds2m',
 '33_4ecb_HUM17586020069902806_1_33_PVwN',
 '33_5ecb_HUM17586020069902806_19_11_aNr4',
 '33_5ecb_HUM17586020069902806_0_8_CtaN',
 '33_5ecb_HUM17586020069902806_19_1_Xtez',
 '33_5ecb_HUM17586020069902806_1_0_6Nzk',
 '33_2ecb_HUM17586062578027048_7_14_boAR',
 '33_1ecb_TIM17633721109929585_0_15_7tvR',
 '33_3ecb_TIM17633721109929585_0_20_F7dw',
 '33_4ecb_TIM17633721109929585_0_28_Ck6z',
 '33_4ecb_TIM17633721109929585_1_19_4cdF',
 '33_5ecb_TIM17633721109929585_19_4_UqKG',
 '33_5ecb_TIM17633721109929585_0_0_KBvT',
 '33_1ecb_HUM17586038555708853_6_12_U6HU',
 '33_1ecb_HUM17586038555708853_2_11_M4Zy',
 '33_2ecb_HUM17586038555708853_7_8_daqd',
 '33_2ecb_HUM17586038555708853_0_8_mMHF',
 '33_3ecb_HUM17586038555708853_0_14_k9WU',
 '33_3ecb_HUM17586038555708853_0_10_G36j',
 '33_3ecb_HUM17586038555708853_5_1_Qs3c',
 '33_3ecb_HUM17586038555708853_0_7_UPp4',
 '33_3ecb_HUM17586038555708853_4_16_GaVK',
 '33_4ecb_HUM17586038555708853_1_25_ZYnk',
 '33_4ecb_HUM17586038555708853_0_15_mpMB',
 '33_4ecb_HUM17586038555708853_1_12_XHbF',
 '33_5ecb_HUM17586038555708853_2_10_3d2a',
 '33_5ecb_HUM17586038555708853_2_18_VFxs',
 '33_1ecb_Singleton_ACTQaKXyxQ_0_22_CQVZ',
 '33_1ecb_Singleton_ACT2oivGmM_1_8_UL9p',
 '33_1ecb_Singleton_ACT54y3B6c_1_4_MsHv',
 '33_1ecb_Singleton_ACTHytbcRQ_2_5_W32Y',
 '33_1ecb_Singleton_ACTGA5Qwih_2_16_MyeF',
 '33_1ecb_Singleton_ACT3gMRUhV_0_41_dF3f',
 '33_1ecb_Singleton_ACToJGmPrL_0_19_iNEr',
 '33_1ecb_Singleton_ACTjyytngQ_6_9_Mrgv',
 '33_1ecb_Singleton_ACTKEQVzhP_1_5_SgSu',
 '33_1ecb_Singleton_ACTXM8ewKK_0_26_4MYL',
 '33_1ecb_Singleton_ACTdXPjBYQ_0_17_e4KT',
 '33_1ecb_Singleton_ACTAsn3wUJ_6_1_gnjn',
 '33_1ecb_Singleton_HUMGSVK6mY_1_7_cNoL',
 '33_1ecb_Singleton_HUMYd5kBY9_6_29_JWM9',
 '33_1ecb_Singleton_HUMM8xthP6_0_18_3syb',
 '33_1ecb_Singleton_HUML289LzR_1_0_QdLL',
 '33_1ecb_Singleton_HUMUvyurP5_1_9_MxQU',
 '33_1ecb_Singleton_HUM2gp7jaY_2_0_aUte',
 '33_1ecb_Singleton_HUMGHLYVi8_2_4_Nw4z',
 '33_1ecb_Singleton_HUMRCoxAqC_6_7_mYuB',
 '33_1ecb_Singleton_LOC3QAPwhe_0_47_NuLu',
 '33_1ecb_Singleton_LOCBUsrbFF_2_22_6HfS',
 '33_1ecb_Singleton_NON4AQeruK_0_44_C5pi',
 '33_1ecb_Singleton_NONJwE5tka_6_23_ZaGk',
 '33_2ecb_Singleton_ACT9svP7Xh_0_18_hPUQ',
 '33_2ecb_Singleton_ACTURtpwDv_7_13_NCuR',
 '33_2ecb_Singleton_ACTcUzuWeh_7_5_JJTB',
 '33_2ecb_Singleton_ACTTQHVtvD_7_10_Vpr9',
 '33_2ecb_Singleton_HUMQooJGeD_7_6_kC8B',
 '33_2ecb_Singleton_HUMJ4FGC3q_7_15_cn7v',
 '33_2ecb_Singleton_NONSJyb5qy_7_3_Ne29',
 '33_2ecb_Singleton_TIMMu6yURx_7_18_MkHL',
 '33_3ecb_Singleton_ACTQBEvaDT_0_9_3ZTw',
 '33_3ecb_Singleton_ACTTvcjUFU_4_10_G2cE',
 '33_3ecb_Singleton_ACTfw65PQF_4_8_UkUH',
 '33_3ecb_Singleton_ACTQtzasEp_4_2_5R8i',
 '33_3ecb_Singleton_ACTd6cUgew_0_25_Y88P',
 '33_3ecb_Singleton_ACTFtMLeQQ_0_27_mnHo',
 '33_3ecb_Singleton_ACTeEx6fKW_46_6_CLtX',
 '33_3ecb_Singleton_ACTADN5mX5_4_14_Zkgx',
 '33_3ecb_Singleton_ACTWbdbp6i_5_8_VeGV',
 '33_3ecb_Singleton_HUMZLJoVBQ_47_0_43sY',
 '33_3ecb_Singleton_HUMJPmhPGU_4_5_ZjJ8',
 '33_3ecb_Singleton_HUM7CCpxEp_46_12_MuW5',
 '33_3ecb_Singleton_NONXjmyffx_47_5_aeK9',
 '33_3ecb_Singleton_TIMh56kBRN_0_24_87GG',
 '33_4ecb_LOC17633757851190902_0_30_4cTe',
 '33_4ecb_Singleton_ACTdoJ8jSv_1_3_Ssf9',
 '33_4ecb_Singleton_ACThYKUWer_1_9_6QJZ',
 '33_4ecb_Singleton_ACTAFL6LoG_1_23_HKA4',
 '33_4ecb_Singleton_ACThAkjEVy_0_5_QwDU',
 '33_4ecb_Singleton_ACT6t36oLi_1_24_by2W',
 '33_4ecb_Singleton_ACTKrsSW6B_1_11_FXRp',
 '33_4ecb_Singleton_ACTWof7cct_0_9_RfhY',
 '33_4ecb_Singleton_ACT6d6nAbo_1_7_CfHB',
 '33_4ecb_Singleton_ACTLDsXbYi_1_4_7yya',
 '33_4ecb_Singleton_HUMEz36CnG_0_8_Q5BK',
 '33_4ecb_Singleton_HUMgxruuHq_1_1_E7PE',
 '33_4ecb_Singleton_LOCoAH5TzZ_1_14_TeMy',
 '33_4ecb_Singleton_LOCi8X7SuQ_1_40_eroF',
 '33_4ecb_Singleton_TIMWXct7kg_0_10_Jxmi',
 '33_4ecb_Singleton_TIMYAP6YA8_1_35_E5T8',
 '33_5ecb_Singleton_ACTfN6dMh3_1_7_iBCJ',
 '33_5ecb_Singleton_ACT5bdVvMQ_1_2_CeGG',
 '33_5ecb_Singleton_ACTKgJBH6h_1_11_4d6F',
 '33_5ecb_Singleton_ACT6y3mjCE_1_14_bMVx',
 '33_5ecb_Singleton_ACT4hGobjh_19_13_nvNZ',
 '33_5ecb_Singleton_ACTNWDBfP6_1_3_gJag',
 '33_5ecb_Singleton_ACTMpJUR4L_2_21_HzMy',
 '33_5ecb_Singleton_ACTEsiCRD3_0_12_BU88',
 '33_5ecb_Singleton_HUMnJTWiYR_1_9_UKGu',
 '33_5ecb_Singleton_HUM4xhfXRt_0_11_EmVG',
 '33_5ecb_Singleton_LOCP7Dgwx7_1_17_oF7a',
 '33_5ecb_Singleton_NON4LZDQgh_1_15_4rZa',
 '33_5ecb_Singleton_NONZkWFsjH_0_16_QkeE',
 '33_5ecb_Singleton_NONbfpAZ3o_2_7_U9X7',
 '33_10ecbplus_HUM17585586231680730_3_9_5ETr',
 '33_1ecbplus_HUM17585586231680730_3_13_ANLk',
 '33_3ecbplus_HUM17585586231680730_1_17_6hgo',
 '33_7ecbplus_HUM17585586231680730_5_21_cy2G',
 '33_10ecbplus_HUM17629205564756179_3_23_DrgC',
 '33_10ecbplus_HUM17629205564756179_3_29_PvvD',
 '33_11ecbplus_HUM17629205564756179_3_26_EnPD',
 '33_3ecbplus_HUM17629205564756179_1_11_VWNh',
 '33_8ecbplus_HUM17629205564756179_5_7_XRCp',
 '33_11ecbplus_TIM17585941511224864_3_18_YYhs',
 '33_2ecbplus_TIM17585941511224864_4_22_nqS6',
 '33_3ecbplus_TIM17585941511224864_8_32_aNrc',
 '33_5ecbplus_TIM17585941511224864_7_28_m9rd',
 '33_7ecbplus_TIM17585941511224864_5_11_hQid',
 '33_7ecbplus_TIM17585941511224864_2_7_Z39Q',
 '33_8ecbplus_TIM17585941511224864_3_19_Qhvd',
 '33_10ecbplus_HUM17585807616836238_1_6_U8Z6',
 '33_10ecbplus_HUM17585807616836238_3_14_FJ2M',
 '33_10ecbplus_HUM17585807616836238_3_16_d7ZU',
 '33_11ecbplus_HUM17585807616836238_3_14_TC5N',
 '33_11ecbplus_HUM17585807616836238_3_16_n38o',
 '33_11ecbplus_HUM17585807616836238_1_5_YzFf',
 '33_11ecbplus_HUM17585807616836238_3_21_3Cq2',
 '33_1ecbplus_HUM17585807616836238_1_2_6pEs',
 '33_1ecbplus_HUM17585807616836238_8_15_bgTq',
 '33_1ecbplus_HUM17585807616836238_3_6_icRj',
 '33_2ecbplus_HUM17585807616836238_1_2_Qz2L',
 '33_2ecbplus_HUM17585807616836238_4_16_Mamu',
 '33_3ecbplus_HUM17585807616836238_1_13_Hmxw',
 '33_3ecbplus_HUM17585807616836238_8_22_2EhP',
 '33_3ecbplus_HUM17585807616836238_1_20_GggN',
 '33_3ecbplus_HUM17585807616836238_1_5_PFCW',
 '33_4ecbplus_HUM17585807616836238_1_4_jrn3',
 '33_4ecbplus_HUM17585807616836238_2_0_g2wW',
 '33_5ecbplus_HUM17585807616836238_3_0_KStF',
 '33_5ecbplus_HUM17585807616836238_1_6_bkEB',
 '33_5ecbplus_HUM17585807616836238_6_12_o4zK',
 '33_5ecbplus_HUM17585807616836238_7_10_KZdz',
 '33_5ecbplus_HUM17585807616836238_2_10_QPCU',
 '33_6ecbplus_HUM17585807616836238_9_20_BfZg',
 '33_6ecbplus_HUM17585807616836238_1_5_ENia',
 '33_6ecbplus_HUM17585807616836238_2_15_VkEC',
 '33_7ecbplus_HUM17585807616836238_5_24_ACQD',
 '33_7ecbplus_HUM17585807616836238_5_13_MxvW',
 '33_7ecbplus_HUM17585807616836238_2_0_HruJ',
 '33_8ecbplus_HUM17585807616836238_6_9_5DkT',
 '33_8ecbplus_HUM17585807616836238_1_13_QUSj',
 '33_8ecbplus_HUM17585807616836238_5_2_grFN',
 '33_8ecbplus_HUM17585807616836238_3_15_GYhT',
 '33_9ecbplus_HUM17585807616836238_3_18_B4C5',
 '33_9ecbplus_HUM17585807616836238_4_22_GE4r',
 '33_9ecbplus_HUM17585807616836238_1_8_m2WC',
 '33_10ecbplus_LOC17621706079932413_1_9_Paqx',
 '33_3ecbplus_LOC17623237064921807_1_24_ahHz',
 '33_7ecbplus_LOC17623237064921807_5_29_WY29',
 '33_10ecbplus_HUM17585547506657721_1_0_UCtW',
 '33_10ecbplus_HUM17585547506657721_3_5_JcsH',
 '33_11ecbplus_HUM17585547506657721_3_32_QCAB',
 '33_11ecbplus_HUM17585547506657721_1_0_6Bxa',
 '33_11ecbplus_HUM17585547506657721_3_6_GJ9Y',
 '33_4ecbplus_HUM17585547506657721_2_8_3TD9',
 '33_5ecbplus_HUM17585547506657721_7_0_Maq2',
 '33_5ecbplus_HUM17585547506657721_7_32_aJ7h',
 '33_5ecbplus_HUM17585547506657721_2_0_WUkQ',
 '33_5ecbplus_HUM17585547506657721_6_16_fuvP',
 '33_5ecbplus_HUM17585547506657721_3_8_Jh5n',
 '33_5ecbplus_HUM17585547506657721_6_1_53LE',
 '33_5ecbplus_HUM17585547506657721_1_0_hqjZ',
 '33_6ecbplus_HUM17585547506657721_1_3_Lt3a',
 '33_6ecbplus_HUM17585547506657721_9_9_KJZg',
 '33_6ecbplus_HUM17585547506657721_2_9_FLKV',
 '33_7ecbplus_HUM17585547506657721_3_9_Mkpr',
 '33_7ecbplus_HUM17585547506657721_3_0_TwpX',
 '33_7ecbplus_HUM17585547506657721_3_8_b78z',
 '33_8ecbplus_HUM17585547506657721_6_3_Ybxo',
 '33_9ecbplus_HUM17585547506657721_4_0_9SaM',
 '33_9ecbplus_HUM17585547506657721_1_2_jpjC',
 '33_9ecbplus_HUM17585547506657721_3_9_GRMg',
 '33_10ecbplus_Singleton_ACTUQadgyQ_3_26_boyD',
 '33_11ecbplus_NON17623222024977927_3_28_c5eP',
 '33_4ecbplus_NON17623222024977927_2_20_C4iK',
 '33_5ecbplus_NON17623222024977927_6_19_SKrU',
 '33_7ecbplus_NON17623222024977927_3_11_fCUD',
 '33_3ecbplus_HUM17621617734760601_8_46_jXyo',
 '33_5ecbplus_HUM17621617734760601_7_23_R2HS',
 '33_5ecbplus_HUM17621590319089619_7_17_oC9B',
 '33_5ecbplus_HUM17623724741679231_3_11_kEuE',
 '33_5ecbplus_HUM17623724741679231_7_35_F3se',
 '33_6ecbplus_HUM17623724741679231_9_14_Z7dR',
 '33_11ecbplus_Singleton_ACTAKHjQRg_3_43_KriT',
 '33_11ecbplus_Singleton_HUMoMBDiya_3_45_nsRn',
 '33_11ecbplus_Singleton_HUM4vweWas_3_42_7YDB',
 '33_11ecbplus_Singleton_HUMGgWLigs_3_39_3yQt',
 '33_2ecbplus_LOC17623163904514133_1_15_k8sT',
 '33_2ecbplus_LOC17623163904514133_4_18_YUT7',
 '33_4ecbplus_LOC17623163904514133_2_21_cxVC',
 '33_5ecbplus_LOC17623163904514133_6_20_bjx9',
 '33_7ecbplus_LOC17623163904514133_3_12_XwUn',
 '33_1ecbplus_HUM17621640789460263_8_0_VgQ7',
 '33_8ecbplus_HUM17621640789460263_3_0_A7e7',
 '33_8ecbplus_HUM17621640789460263_1_0_RdNM',
 '33_1ecbplus_HUM17621629780480551_8_11_hQxN',
 '33_2ecbplus_HUM17621629780480551_4_12_UPr9',
 '33_2ecbplus_HUM17621629780480551_1_12_kzh6',
 '33_4ecbplus_HUM17621629780480551_1_0_n9tg',
 '33_4ecbplus_HUM17621629780480551_1_1_VaZD',
 '33_8ecbplus_HUM17621629780480551_3_9_ZeR2',
 '33_9ecbplus_HUM17621629780480551_3_12_6xvg',
 '33_1ecbplus_NON17623252089210976_1_0_b3nb',
 '33_1ecbplus_NON17623252089210976_8_4_8Wfv',
 '33_1ecbplus_NON17623252089210976_3_0_SekE',
 '33_2ecbplus_NON17623252089210976_4_2_Pt2j',
 '33_2ecbplus_NON17623252089210976_1_0_hHRN',
 '33_3ecbplus_NON17623252089210976_8_3_YzHC',
 '33_7ecbplus_NON17623252089210976_5_2_UtBF',
 '33_8ecbplus_NON17623252089210976_1_3_5DgS',
 '33_8ecbplus_NON17623252089210976_3_4_MJ9R',
 '33_6ecbplus_HUM17585723434196928_9_18_YzBq',
 '33_1ecbplus_Singleton_ACT8TYD6eE_3_8_K4ep',
 '33_1ecbplus_Singleton_ACTQSYnUPJ_3_19_Mc2H',
 '33_1ecbplus_Singleton_HUMWKsBfy2_3_22_oNxV',
 '33_1ecbplus_Singleton_TIMcBeaZRD_3_17_8kMf',
 '33_3ecbplus_HUM18263985267193908_1_0_jqUd',
 '33_6ecbplus_HUM18263985267193908_2_1_NMxU',
 '33_9ecbplus_HUM18263985267193908_3_1_8MUb',
 '33_9ecbplus_HUM18263985267193908_1_0_nJy3',
 '33_4ecbplus_HUM17585569357878445_2_13_TaGt',
 '33_6ecbplus_HUM17585569357878445_9_11_d9Yw',
 '33_8ecbplus_HUM17585569357878445_6_6_kA4M',
 '33_3ecbplus_HUM17621675062197017_1_23_Yifz',
 '33_7ecbplus_HUM17621675062197017_5_27_ksVb',
 '33_3ecbplus_HUM17585842183770407_8_36_9Xx9',
 '33_6ecbplus_HUM17585842183770407_2_21_CT3L',
 '33_6ecbplus_HUM17585842183770407_9_23_gga5',
 '33_3ecbplus_Singleton_ACTDNCpvd9_1_14_R9kq',
 '33_3ecbplus_Singleton_ACTBb9ExKr_1_8_Bcn3',
 '33_3ecbplus_Singleton_HUMdpgLUwA_8_18_d499',
 '33_3ecbplus_Singleton_LOCX2pyTiG_8_6_K4zo',
 '33_3ecbplus_Singleton_TIMezmimKD_8_11_cLRh',
 '33_4ecbplus_Singleton_ACTCNdUVJL_1_9_Z2Do',
 '33_4ecbplus_Singleton_ACTHpMym8k_2_30_GcfR',
 '33_4ecbplus_Singleton_NONNytSgU5_2_33_miqU',
 '33_4ecbplus_Singleton_NONP93MiD9_2_29_88Yv',
 '33_5ecbplus_Singleton_NON3FZjsPF_3_6_8f27',
 '33_5ecbplus_Singleton_TIMdW596NU_6_5_RpwG',
 '33_6ecbplus_Singleton_ACTYjFxo87_9_2_SE5x',
 '33_7ecbplus_Singleton_ACT7YGEYNx_2_14_76R2',
 '33_7ecbplus_Singleton_ACToXuKVLm_5_25_Va97',
 '33_7ecbplus_Singleton_LOCQiJaPJk_2_15_edkS',
 '33_7ecbplus_Singleton_TIM2BJa8Pz_5_8_LpBf',
 '33_7ecbplus_Singleton_TIMWgAJWQU_2_20_RL2T',
 '33_8ecbplus_Singleton_HUMPN6b5CJ_6_0_hUAv',
 '33_8ecbplus_Singleton_HUMMMNsLhR_5_0_CAw3',
 '33_9ecbplus_Singleton_ACT5CGCBRP_4_6_gDcY',
 '33_9ecbplus_Singleton_ACT3nx6W6C_4_14_enVd',
 '33_1ecb_ACT27398610578363208_6_19_aS9Q',
 '33_2ecb_ACT27398610578363208_7_27_YYMu',
 '33_2ecb_ACT27398610578363208_0_12_m6eB',
 '33_1ecb_ACT27398642960429027_0_36_b5qH',
 '33_1ecb_ACT27398642960429027_1_15_bDsv',
 '33_3ecb_ACT27398642960429027_46_16_h9wf',
 '33_3ecb_ACT27398642960429027_47_1_NXQ6',
 '33_3ecb_ACT27398642960429027_46_3_DB7r',
 '33_3ecb_ACT27398642960429027_49_4_VHh4',
 '33_4ecb_ACT27398642960429027_1_32_gL3F',
 '33_1ecb_ACT17586104998270489_0_6_3tSL',
 '33_2ecb_ACT17586104998270489_0_13_iTKE',
 '33_3ecb_ACT17586104998270489_0_16_Lops',
 '33_4ecb_ACT17586104998270489_0_24_HtNF',
 '33_5ecb_ACT17586104998270489_19_3_ixhL',
 '33_5ecb_ACT17586104998270489_1_1_ShUV',
 '33_5ecb_ACT17586104998270489_0_6_N6aq',
 '33_1ecb_ACT27400243519478655_6_31_n5EV',
 '33_1ecb_ACT27400243519478655_2_18_KrLn',
 '33_3ecb_ACT27400243519478655_5_2_bS4E',
 '33_3ecb_ACT27400243519478655_4_17_iva9',
 '33_4ecb_ACT27400243519478655_0_22_jaBJ',
 '33_4ecb_ACT27400243519478655_1_28_4tuy',
 '33_4ecb_ACT27400243519478655_1_39_7QW8',
 '33_5ecb_ACT27400243519478655_2_13_9zeD',
 '33_1ecb_ACT17633219253735150_2_8_FEp5',
 '33_2ecb_ACT17633219253735150_0_3_2GPt',
 '33_4ecb_ACT17633219253735150_0_13_LBho',
 '33_5ecb_ACT17633219253735150_2_23_iraX',
 '33_2ecb_ACT17633195816649614_0_9_huxn',
 '33_4ecb_ACT17633195816649614_0_20_gkEw',
 '33_5ecb_ACT17633195816649614_2_11_Gfp6',
 '33_2ecb_ACT17633296211137795_0_0_WwFy',
 '33_3ecb_ACT17633296211137795_0_30_4WMM',
 '33_4ecb_ACT17633296211137795_0_1_f6w7',
 '33_10ecbplus_ACT17585255017659433_1_10_bxjD',
 '33_11ecbplus_ACT17585255017659433_1_3_4zeU',
 '33_11ecbplus_ACT17585255017659433_3_37_G3Y3',
 '33_11ecbplus_ACT17585255017659433_3_11_FNPT',
 '33_1ecbplus_ACT17585255017659433_3_14_Hixs',
 '33_1ecbplus_ACT17585255017659433_1_4_aEnL',
 '33_2ecbplus_ACT17585255017659433_1_16_gZFb',
 '33_3ecbplus_ACT17585255017659433_1_18_8m97',
 '33_4ecbplus_ACT17585255017659433_1_8_jRCj',
 '33_6ecbplus_ACT17585255017659433_9_31_h2ad',
 '33_7ecbplus_ACT17585255017659433_5_22_BzLr',
 '33_10ecbplus_ACT17585325371238934_3_19_gvT2',
 '33_10ecbplus_ACT17585325371238934_3_28_aXwx',
 '33_11ecbplus_ACT17585325371238934_3_22_QQE3',
 '33_3ecbplus_ACT17585325371238934_1_9_TaQD',
 '33_8ecbplus_ACT17585325371238934_5_6_izjE',
 '33_10ecbplus_ACT17585266691851703_3_11_CSTo',
 '33_10ecbplus_ACT17585266691851703_1_4_CSFN',
 '33_11ecbplus_ACT17585266691851703_3_17_gxjo',
 '33_1ecbplus_ACT17585266691851703_3_10_Bu7o',
 '33_1ecbplus_ACT17585266691851703_8_14_fQyW',
 '33_2ecbplus_ACT17585266691851703_4_15_fjRk',
 '33_2ecbplus_ACT17585266691851703_1_4_8Qrr',
 '33_3ecbplus_ACT17585266691851703_1_7_JAwE',
 '33_3ecbplus_ACT17585266691851703_8_21_atoD',
 '33_4ecbplus_ACT17585266691851703_1_3_ZhU9',
 '33_4ecbplus_ACT17585266691851703_2_3_DxUv',
 '33_5ecbplus_ACT17585266691851703_3_2_5QP4',
 '33_5ecbplus_ACT17585266691851703_1_4_bwFu',
 '33_5ecbplus_ACT17585266691851703_6_7_mQPv',
 '33_5ecbplus_ACT17585266691851703_7_9_hfWq',
 '33_5ecbplus_ACT17585266691851703_2_8_KpMy',
 '33_6ecbplus_ACT17585266691851703_9_26_k3Ws',
 '33_6ecbplus_ACT17585266691851703_2_13_QqWh',
 '33_7ecbplus_ACT17585266691851703_5_18_eEZH',
 '33_7ecbplus_ACT17585266691851703_2_6_ZUPj',
 '33_8ecbplus_ACT17585266691851703_6_10_AcuQ',
 '33_8ecbplus_ACT17585266691851703_5_3_kJjR',
 '33_8ecbplus_ACT17585266691851703_3_13_em54',
 '33_9ecbplus_ACT17585266691851703_1_6_BKbB',
 '33_9ecbplus_ACT17585266691851703_3_16_3MwZ',
 '33_9ecbplus_ACT17585266691851703_4_20_Tji9',
 '33_10ecbplus_ACT17585287225701179_1_2_Ztgy',
 '33_10ecbplus_ACT17585287225701179_3_6_JjJc',
 '33_11ecbplus_ACT17585287225701179_3_9_7p9Q',
 '33_11ecbplus_ACT17585338576001952_1_1_JJVt',
 '33_10ecbplus_ACT17585959125368141_3_17_ak4n',
 '33_8ecbplus_ACT17585959125368141_5_4_3cSX',
 '33_11ecbplus_NEG17585310111174350_3_35_XUbP',
 '33_3ecbplus_ACT17585857916290598_8_35_giRn',
 '33_5ecbplus_ACT17585857916290598_7_16_RgXC',
 '33_6ecbplus_ACT17585857916290598_2_19_dhfd',
 '33_6ecbplus_ACT17585857916290598_9_28_BZuA',
 '33_7ecbplus_ACT17623186389747222_3_7_WuCp',
 '33_11ecbplus_ACT17585354950477601_3_31_PksZ',
 '33_1ecbplus_ACT17623263540391653_8_1_Zce3',
 '33_1ecbplus_ACT17623263540391653_3_16_5u7G',
 '33_1ecbplus_ACT17623263540391653_1_6_D9km',
 '33_2ecbplus_ACT17623263540391653_1_7_6XfU',
 '33_2ecbplus_ACT17623263540391653_4_4_icnE',
 '33_3ecbplus_ACT17623263540391653_8_5_jZYM',
 '33_3ecbplus_ACT17623263540391653_1_1_KUEg',
 '33_7ecbplus_ACT17623263540391653_5_3_gaMe',
 '33_8ecbplus_ACT17623263540391653_1_1_GTRK',
 '33_8ecbplus_ACT17623263540391653_3_2_2UtX',
 '33_1ecbplus_ACT17628957613559298_8_12_hDdh',
 '33_2ecbplus_ACT17628957613559298_4_13_WsRh',
 '33_2ecbplus_ACT17628957613559298_1_13_R8UF',
 '33_3ecbplus_ACT17628957613559298_8_19_aB84',
 '33_4ecbplus_ACT17628957613559298_2_6_dNht',
 '33_8ecbplus_ACT17628957613559298_3_11_VauE',
 '33_8ecbplus_ACT17628957613559298_6_2_ixGS',
 '33_9ecbplus_ACT17628957613559298_3_14_e3vv',
 '33_1ecbplus_ACT17585751797652339_8_7_5qWL',
 '33_1ecbplus_ACT17585751797652339_1_8_8ibU',
 '33_2ecbplus_ACT17585751797652339_4_8_mE7y',
 '33_2ecbplus_ACT17585751797652339_1_9_ZtJf',
 '33_3ecbplus_ACT17585751797652339_8_15_UcGc',
 '33_4ecbplus_ACT17585751797652339_1_10_AEwn',
 '33_6ecbplus_ACT17585751797652339_9_7_Rv6z',
 '33_8ecbplus_ACT17585751797652339_1_5_JzfW',
 '33_8ecbplus_ACT17585751797652339_3_7_bepf',
 '33_4ecbplus_ACT17623175679638697_2_19_2Qex',
 '33_5ecbplus_ACT17623175679638697_6_17_FXrw',
 '33_7ecbplus_ACT17623175679638697_3_10_gwSY',
 '33_7ecbplus_ACT17623280700408927_5_9_KFuw',
 '33_3ecbplus_ACTUfEKvC9HF9VsCksXH_1_21_FMP8',
 '33_5ecbplus_ACT17628981134789602_7_33_JDow',
 '33_5ecbplus_ACT17628981134789602_3_9_7c35',
 '33_6ecbplus_ACT17628981134789602_9_13_nASQ',
 '33_5ecbplus_ACT17585828057143307_1_2_aHf2',
 '33_5ecbplus_ACT17585828057143307_2_6_3ks5',
 '33_5ecbplus_ACT17585828057143307_7_7_JiPh',
 '33_6ecbplus_ACT17585828057143307_2_6_eCut',
 '33_6ecbplus_ACT17585828057143307_1_0_D3Du',
 '33_9ecbplus_ACT17585828057143307_1_4_UmS5',
 '33_9ecbplus_ACT17585828057143307_4_4_jiXS',
 '33_9ecbplus_ACT17585828057143307_3_6_QVe8',
 '33_5ecbplus_ACT17585774063009451_7_6_HZYo',
 '33_5ecbplus_ACT17585774063009451_6_4_Shjv',
 '33_5ecbplus_ACT17585774063009451_2_5_ZYkj',
 '33_6ecbplus_ACT17585774063009451_1_1_9iHE',
 '33_6ecbplus_ACT17585774063009451_2_7_hoJC',
 '33_9ecbplus_ACT17585774063009451_1_1_oAGC',
 '33_9ecbplus_ACT17585774063009451_4_3_G9Fm',
 '33_9ecbplus_ACT17585774063009451_3_7_MDxf',
 '33_6ecbplus_ACT17585762433036633_9_5_mFNA',
 '33_6ecbplus_ACT17585785761378653_2_4_ZN4Z',
 '33_9ecbplus_ACT17585785761378653_3_3_foEu']

In [43]:
cdcr_test.sentences['1/1ecb/1'][0]

{0: 'Another',
 1: 'day',
 2: 'in',
 3: 'Hollywood',
 4: ';',
 5: 'another',
 6: 'star',
 7: 'in',
 8: 'rehab',
 9: '.'}

In [44]:
tt={0: 'Another',
 1: 'day',
 2: 'in',
 3: 'Hollywood',
 4: ';',
 5: 'another',
 8: 'star',
 7: 'in',
 6: 'rehab',
 9: '.'}

In [45]:
sorted_values = [value for _, value in sorted(tt.items())]

print(sorted_values)

['Another', 'day', 'in', 'Hollywood', ';', 'another', 'rehab', 'in', 'star', '.']

In [15]:
[1,2,3] + [4,5]

[1, 2, 3, 4, 5]

In [5]:
mention.new_context

[1, 2]

In [23]:
possible_sentences = [0,1,2]
if mention.sent_id in possible_sentences:
    possible_sentences.pop(mention.sent_id)
else:
    possible_sentences.pop()
possible_sentences

[1, 2]

In [21]:
mention.sent_id

0

In [6]:
cdcr_test.mentions_by_topics['1']

['1_10ecb_TIM16236441119149059_3_11_YJuG',
 '1_11ecb_TIM16236441119149059_0_20_jzZQ',
 '1_14ecb_TIM16236441119149059_1_18_d7zS',
 '1_15ecb_TIM16236441119149059_1_0_ngQo',
 '1_15ecb_TIM16236441119149059_1_2_27Zv',
 '1_5ecb_TIM16236441119149059_3_4_hBaQ',
 '1_7ecb_TIM16236441119149059_1_12_k9bR',
 '1_8ecb_TIM16236441119149059_1_35_A87Z',
 '1_10ecb_HUM16284637796168708_0_13_kBiF',
 '1_11ecb_HUM16284637796168708_0_13_HrUc',
 '1_11ecb_HUM16284637796168708_2_14_e9jk',
 '1_14ecb_HUM16284637796168708_2_24_h2sb',
 '1_14ecb_HUM16284637796168708_1_22_2E9c',
 '1_17ecb_HUM16284637796168708_2_20_63Qo',
 '1_18ecb_HUM16284637796168708_0_28_7LGi',
 '1_19ecb_HUM16284637796168708_3_13_LzRS',
 '1_1ecb_HUM16284637796168708_2_5_7MEN',
 '1_2ecb_HUM16284637796168708_0_1_38jb',
 '1_2ecb_HUM16284637796168708_2_0_HfmP',
 '1_3ecb_HUM16284637796168708_1_21_JC6T',
 '1_4ecb_HUM16284637796168708_2_5_XH6A',
 '1_5ecb_HUM16284637796168708_1_6_TRkm',
 '1_5ecb_HUM16284637796168708_2_21_T9Vq',
 '1_6ecb_HUM16284637796168708_1_10_kb7d',
 '1_6ecb_HUM16284637796168708_0_5_fJyB',
 '1_7ecb_HUM16284637796168708_4_2_HynK',
 '1_10ecb_HUM16236907954762763_0_15_cg5u',
 '1_10ecb_HUM16236907954762763_3_6_f2SX',
 '1_11ecb_HUM16236907954762763_0_16_B3MU',
 '1_14ecb_HUM16236907954762763_1_24_9DSQ',
 '1_1ecb_HUM16236907954762763_1_3_biJw',
 '1_1ecb_HUM16236907954762763_2_0_7Wtt',
 '1_5ecb_HUM16236907954762763_2_24_E6G9',
 '1_6ecb_HUM16236907954762763_0_2_o3Xe',
 '1_7ecb_HUM16236907954762763_4_15_TGiB',
 '1_8ecb_HUM16236907954762763_1_2_bm7h',
 '1_10ecb_HUM17392465282479574_3_18_Z5kV',
 '1_17ecb_HUM17392465282479574_2_8_8F2U',
 '1_5ecb_HUM17392465282479574_2_9_d6ek',
 '1_6ecb_HUM17392465282479574_1_6_Lov8',
 '1_10ecb_HUM16236184328979740_0_6_MD8p',
 '1_10ecb_HUM16236184328979740_3_7_U3qD',
 '1_10ecb_HUM16236184328979740_3_20_giQy',
 '1_10ecb_HUM16236184328979740_0_3_TqQk',
 '1_11ecb_HUM16236184328979740_2_5_Mc5j',
 '1_11ecb_HUM16236184328979740_0_0_DMbY',
 '1_11ecb_HUM16236184328979740_2_1_ejJu',
 '1_12ecb_HUM16236184328979740_1_0_FGoe',
 '1_13ecb_HUM16236184328979740_1_2_bKXd',
 '1_13ecb_HUM16236184328979740_1_11_Pgq9',
 '1_14ecb_HUM16236184328979740_2_19_JpXv',
 '1_14ecb_HUM16236184328979740_5_8_HM4C',
 '1_14ecb_HUM16236184328979740_5_4_CqzY',
 '1_14ecb_HUM16236184328979740_2_4_4RjK',
 '1_14ecb_HUM16236184328979740_2_12_ngzN',
 '1_14ecb_HUM16236184328979740_2_32_RJew',
 '1_14ecb_HUM16236184328979740_5_1_cNUq',
 '1_14ecb_HUM16236184328979740_0_0_6Zk7',
 '1_14ecb_HUM16236184328979740_1_9_aUzj',
 '1_15ecb_HUM16236184328979740_0_4_dmjw',
 '1_15ecb_HUM16236184328979740_0_14_4FZu',
 '1_15ecb_HUM16236184328979740_1_5_9VUi',
 '1_15ecb_HUM16236184328979740_1_8_5smN',
 '1_15ecb_HUM16236184328979740_1_18_29tS',
 '1_17ecb_HUM16236184328979740_1_1_ARfy',
 '1_17ecb_HUM16236184328979740_0_5_8yuu',
 '1_17ecb_HUM16236184328979740_2_5_5zxC',
 '1_18ecb_HUM16236184328979740_0_9_MMrF',
 '1_18ecb_HUM16236184328979740_0_5_2L8D',
 '1_18ecb_HUM16236184328979740_0_3_VXpt',
 '1_19ecb_HUM16236184328979740_3_4_9ht9',
 '1_19ecb_HUM16236184328979740_1_3_XSZQ',
 '1_19ecb_HUM16236184328979740_1_1_Zrua',
 '1_19ecb_HUM16236184328979740_0_0_EcCy',
 '1_19ecb_HUM16236184328979740_3_0_eALW',
 '1_1ecb_HUM16236184328979740_1_16_CKc3',
 '1_1ecb_HUM16236184328979740_1_11_ZXEq',
 '1_1ecb_HUM16236184328979740_2_9_hkGu',
 '1_2ecb_HUM16236184328979740_2_5_jNZA',
 '1_2ecb_HUM16236184328979740_2_12_3uKQ',
 '1_2ecb_HUM16236184328979740_0_7_YqTQ',
 '1_2ecb_HUM16236184328979740_0_3_RMha',
 '1_3ecb_HUM16236184328979740_1_5_VDXG',
 '1_3ecb_HUM16236184328979740_1_3_8kYp',
 '1_4ecb_HUM16236184328979740_2_16_jUGt',
 '1_4ecb_HUM16236184328979740_1_1_gAEu',
 '1_4ecb_HUM16236184328979740_2_12_3LNt',
 '1_5ecb_HUM16236184328979740_1_3_GfTe',
 '1_5ecb_HUM16236184328979740_1_11_4dXn',
 '1_5ecb_HUM16236184328979740_2_6_Zcae',
 '1_5ecb_HUM16236184328979740_3_2_WwBV',
 '1_5ecb_HUM16236184328979740_3_0_GyK3',
 '1_6ecb_HUM16236184328979740_0_8_T6fm',
 '1_6ecb_HUM16236184328979740_0_15_Cxbh',
 '1_6ecb_HUM16236184328979740_0_19_AK2W',
 '1_6ecb_HUM16236184328979740_1_16_UmHH',
 '1_6ecb_HUM16236184328979740_1_3_MmT4',
 '1_7ecb_HUM16236184328979740_2_1_YgTn',
 '1_7ecb_HUM16236184328979740_2_5_2h9U',
 '1_7ecb_HUM16236184328979740_1_1_CZh4',
 '1_7ecb_HUM16236184328979740_4_20_oVqY',
 '1_7ecb_HUM16236184328979740_5_4_J6Ar',
 '1_7ecb_HUM16236184328979740_5_0_BjoD',
 '1_7ecb_HUM16236184328979740_0_5_9HzV',
 '1_7ecb_HUM16236184328979740_4_7_UnWw',
 '1_8ecb_HUM16236184328979740_1_6_QvoU',
 '1_8ecb_HUM16236184328979740_1_28_PNdC',
 '1_9ecb_HUM16236184328979740_4_4_8DDd',
 '1_9ecb_HUM16236184328979740_3_14_iqiV',
 '1_9ecb_HUM16236184328979740_3_1_SjCj',
 '1_10ecb_LOC16235213289813758_3_10_KK6F',
 '1_10ecb_LOC16235213289813758_0_8_Aefn',
 '1_11ecb_LOC16235213289813758_2_7_2uZi',
 '1_11ecb_LOC16235213289813758_0_5_RfJn',
 '1_12ecb_LOC16235213289813758_1_5_gqeT',
 '1_13ecb_LOC16235213289813758_1_17_AwcP',
 '1_14ecb_LOC16235213289813758_1_14_2Ndg',
 '1_14ecb_LOC16235213289813758_0_5_hvTy',
 '1_14ecb_LOC16235213289813758_2_35_iYxj',
 '1_15ecb_LOC16235213289813758_0_16_AazV',
 '1_17ecb_LOC16235213289813758_1_7_kzM5',
 '1_18ecb_LOC16235213289813758_0_20_LAgn',
 '1_19ecb_LOC16235213289813758_3_6_Yjy7',
 '1_19ecb_LOC16235213289813758_0_5_j6KD',
 '1_1ecb_LOC16235213289813758_1_47_H9WT',
 '1_1ecb_LOC16235213289813758_1_36_TrkJ',
 '1_1ecb_LOC16235213289813758_2_12_REdx',
 '1_2ecb_LOC16235213289813758_0_9_CCqT',
 '1_2ecb_LOC16235213289813758_2_14_Uur3',
 '1_3ecb_LOC16235213289813758_1_10_MCMH',
 '1_4ecb_LOC16235213289813758_2_18_Uva2',
 '1_4ecb_LOC16235213289813758_1_21_dBmP',
 '1_5ecb_LOC16235213289813758_1_14_LnSA',
 '1_6ecb_LOC16235213289813758_0_22_8kE8',
 '1_7ecb_LOC16235213289813758_1_7_GWX7',
 '1_7ecb_LOC16235213289813758_2_7_4T9w',
 '1_7ecb_LOC16235213289813758_0_8_DjJD',
 '1_7ecb_LOC16235213289813758_4_9_38Zx',
 '1_8ecb_LOC16235213289813758_1_32_YHHs',
 '1_9ecb_LOC16235213289813758_3_8_W6FX',
 '1_9ecb_LOC16235213289813758_4_9_6Yaf',
 '1_10ecb_Singleton_ACTd692Zmb_3_19_kiAh',
 '1_10ecb_Singleton_ACTZxKM6hP_3_5_Pfhx',
 '1_10ecb_Singleton_HUM2pcTELr_3_1_DZA8',
 '1_10ecb_Singleton_HUM7jMtdKo_3_16_EPSz',
 '1_11ecb_HUM16238359925764052_2_16_Y8LL',
 '1_11ecb_HUM16238359925764052_0_18_ftZN',
 '1_12ecb_Singleton_LOCMnswMwB_1_13_D5oL',
 '1_13ecb_Singleton_ACT9TxVjZw_1_10_fLnk',
 '1_13ecb_Singleton_HUMfQg7hPC_1_12_kdm3',
 '1_13ecb_Singleton_NON5SSPkab_1_13_ajsq',
 '1_14ecb_Singleton_ACTYxYJpBy_2_8_R2Go',
 '1_14ecb_Singleton_ACTjfp8bp8_0_8_TV3A',
 '1_14ecb_Singleton_ACTJmNqvHT_2_13_V7CK',
 '1_15ecb_Singleton_ACT4jYvkbb_1_9_4ZFD',
 '1_15ecb_Singleton_ACTXknCKJ4_0_7_DMif',
 '1_15ecb_Singleton_ACTMVWf9sE_1_7_maTc',
 '1_15ecb_Singleton_TIM7KvqpLu_0_10_JNDM',
 '1_17ecb_HUM16190455117756553_2_0_HTGG',
 '1_5ecb_HUM16190455117756553_2_1_AMDU',
 '1_17ecb_HUM16285687682097521_0_13_MshB',
 '1_17ecb_HUM16285687682097521_2_23_oHGa',
 '1_17ecb_HUM16190472604309407_2_2_WuUi',
 '1_17ecb_Singleton_ACTdLFmbfm_0_17_bQwc',
 '1_18ecb_NON16235259290300144_0_7_b2Xj',
 '1_18ecb_NON16235236247965825_0_15_BbWH',
 '1_18ecb_Singleton_ACTYQJHF8c_0_6_Ge93',
 '1_19ecb_NON16285643294051965_1_10_F2T2',
 '1_3ecb_NON16285643294051965_1_1_Yhvq',
 '1_6ecb_NON16285643294051965_1_19_ddxH',
 '1_7ecb_NON16285643294051965_5_9_HcQw',
 '1_7ecb_NON16285643294051965_0_2_3B5C',
 '1_8ecb_NON16285643294051965_1_20_bevu',
 '1_19ecb_Singleton_TIMeNrcMuV_1_17_Bvu3',
 '1_1ecb_Singleton_ACTWx7B7aU_1_24_dPy5',
 '1_1ecb_Singleton_ACT5RBRE9x_1_58_ZtJn',
 '1_1ecb_Singleton_ACThpeGu9u_1_1_KJki',
 '1_1ecb_Singleton_HUM8BKnLwX_1_63_REBP',
 '1_1ecb_Singleton_NONPLWmwwQ_1_20_QVaR',
 '1_1ecb_Singleton_NON2NeEjRj_1_30_QdNS',
 '1_1ecb_Singleton_NON4tyvf6q_1_0_mgBK',
 '1_4ecb_LOC16236215950002324_1_8_6Hq2',
 '1_4ecb_Singleton_ACT8cKpzLq_1_7_away',
 '1_4ecb_Singleton_NONo6EskQJ_1_15_Uayk',
 '1_6ecb_Singleton_ACTPDZLUru_1_0_SEoU',
 '1_6ecb_Singleton_ACTTwGDv6p_1_2_7P4J',
 '1_6ecb_Singleton_NON2woMP7P_1_24_MQY3',
 '1_6ecb_Singleton_NONbeRfFJ5_1_29_hbb6',
 '1_7ecb_NON16285702960183809_5_19_BDEe',
 '1_7ecb_Singleton_ACT3pK5ZVK_4_16_GNHB',
 '1_7ecb_Singleton_HUMXaWLnDW_4_12_fd6h',
 '1_7ecb_Singleton_NONSbFrRHF_5_6_WLwH',
 '1_7ecb_Singleton_TIMZtyYHy4_5_21_RKiM',
 '1_8ecb_Singleton_ACTA2YDQEe_1_12_5PJm',
 '1_8ecb_Singleton_ACTgjTPCkB_1_15_8z6U',
 '1_8ecb_Singleton_ACTQxgJeNJ_1_1_XkXL',
 '1_8ecb_Singleton_NEGXTM5QfA_1_10_3jhH',
 '1_8ecb_Singleton_TIM54wWUkr_1_3_9mzf',
 '1_9ecb_Singleton_HUMekzZ43e_4_15_6xNE',
 '1_10ecbplus_TIM15737539387899295_3_33_PNjr',
 '1_13ecbplus_TIM15737539387899295_3_10_MZQA',
 '1_13ecbplus_TIM15737539387899295_1_7_c2SE',
 '1_14ecbplus_TIM15737539387899295_4_24_Kt3B',
 '1_1ecbplus_TIM15737539387899295_4_30_9yMp',
 '1_7ecbplus_TIM15737539387899295_3_28_oR4r',
 '1_10ecbplus_LOC15734326865367655_3_26_7Q7T',
 '1_10ecbplus_LOC15734326865367655_1_4_27Ri',
 '1_11ecbplus_LOC15734326865367655_5_4_nBS6',
 '1_11ecbplus_LOC15734326865367655_2_10_jDxq',
 '1_11ecbplus_LOC15734326865367655_1_5_J5Ae',
 '1_14ecbplus_LOC15734326865367655_4_4_jULm',
 '1_14ecbplus_LOC15734326865367655_1_8_6iwA',
 '1_14ecbplus_LOC15734326865367655_1_4_bU3P',
 '1_15ecbplus_LOC15734326865367655_3_25_Bpdy',
 '1_15ecbplus_LOC15734326865367655_1_4_h8Fv',
 '1_17ecbplus_LOC15734326865367655_1_5_SAgz',
 '1_17ecbplus_LOC15734326865367655_4_22_3hco',
 '1_19ecbplus_LOC15734326865367655_3_15_4jnE',
 '1_19ecbplus_LOC15734326865367655_4_21_Q2tX',
 '1_19ecbplus_LOC15734326865367655_1_4_9jff',
 '1_1ecbplus_LOC15734326865367655_3_4_fRuV',
 '1_1ecbplus_LOC15734326865367655_1_3_2UPs',
 '1_20ecbplus_LOC15734326865367655_3_7_VcP5',
 '1_20ecbplus_LOC15734326865367655_1_4_4zUP',
 '1_3ecbplus_LOC15734326865367655_1_5_krbM',
 '1_3ecbplus_LOC15734326865367655_3_4_3rdv',
 '1_6ecbplus_LOC15734326865367655_3_22_RuVr',
 '1_6ecbplus_LOC15734326865367655_1_5_LGTk',
 '1_8ecbplus_LOC15734326865367655_7_4_Yah2',
 '1_8ecbplus_LOC15734326865367655_6_10_msWu',
 '1_9ecbplus_LOC15734326865367655_2_19_cu9K',
 '1_9ecbplus_LOC15734326865367655_1_3_hc95',
 '1_10ecbplus_HUM15732980283919140_3_18_joEZ',
 '1_10ecbplus_HUM15732980283919140_3_21_AJeu',
 '1_10ecbplus_HUM15732980283919140_1_0_WCtc',
 '1_11ecbplus_HUM15732980283919140_2_1_eUkN',
 '1_11ecbplus_HUM15732980283919140_5_0_XZNj',
 '1_11ecbplus_HUM15732980283919140_1_0_GEux',
 '1_11ecbplus_HUM15732980283919140_5_20_DUxC',
 '1_12ecbplus_HUM15732980283919140_1_0_3ZBT',
 '1_12ecbplus_HUM15732980283919140_3_22_KrTc',
 '1_12ecbplus_HUM15732980283919140_3_6_NeLP',
 '1_12ecbplus_HUM15732980283919140_3_39_39Ef',
 '1_13ecbplus_HUM15732980283919140_3_0_ECsv',
 '1_13ecbplus_HUM15732980283919140_1_0_4WBH',
 '1_14ecbplus_HUM15732980283919140_4_0_mJZL',
 '1_14ecbplus_HUM15732980283919140_1_9_EKbs',
 '1_14ecbplus_HUM15732980283919140_4_30_5W8Q',
 '1_14ecbplus_HUM15732980283919140_1_0_GjYz',
 '1_15ecbplus_HUM15732980283919140_3_23_aHxw',
 '1_15ecbplus_HUM15732980283919140_1_0_X47j',
 '1_15ecbplus_HUM15732980283919140_3_20_WJxk',
 '1_16ecbplus_HUM15732980283919140_3_0_YJLi',
 '1_16ecbplus_HUM15732980283919140_1_0_bW5j',
 '1_16ecbplus_HUM15732980283919140_3_28_jM9X',
 '1_17ecbplus_HUM15732980283919140_1_0_4YdT',
 '1_17ecbplus_HUM15732980283919140_4_19_J2Bc',
 '1_18ecbplus_HUM15732980283919140_3_0_HPh7',
 '1_18ecbplus_HUM15732980283919140_4_0_S7YB',
 '1_18ecbplus_HUM15732980283919140_4_17_hG2Q',
 '1_18ecbplus_HUM15732980283919140_1_0_QB2M',
 '1_19ecbplus_HUM15732980283919140_3_18_9rjz',
 '1_19ecbplus_HUM15732980283919140_4_15_VBv2',
 '1_19ecbplus_HUM15732980283919140_1_0_XvYL',
 '1_19ecbplus_HUM15732980283919140_3_5_n96o',
 '1_1ecbplus_HUM15732980283919140_5_0_7RX8',
 '1_1ecbplus_HUM15732980283919140_1_0_b5nq',
 '1_1ecbplus_HUM15732980283919140_3_0_TFn2',
 '1_1ecbplus_HUM15732980283919140_4_25_3T3C',
 '1_20ecbplus_HUM15732980283919140_4_3_Mfmc',
 '1_20ecbplus_HUM15732980283919140_4_17_gZtV',
 '1_20ecbplus_HUM15732980283919140_1_0_mMfw',
 '1_20ecbplus_HUM15732980283919140_3_23_4N9W',
 '1_20ecbplus_HUM15732980283919140_3_0_HK9e',
 '1_21ecbplus_HUM15732980283919140_7_19_PLXM',
 '1_21ecbplus_HUM15732980283919140_3_11_D4Xs',
 '1_21ecbplus_HUM15732980283919140_1_2_kHwp',
 '1_21ecbplus_HUM15732980283919140_3_20_SWjf',
 '1_21ecbplus_HUM15732980283919140_5_0_5KUf',
 '1_21ecbplus_HUM15732980283919140_7_7_gwta',
 '1_21ecbplus_HUM15732980283919140_3_0_LLAS',
 '1_2ecbplus_HUM15732980283919140_2_2_JQE5',
 '1_2ecbplus_HUM15732980283919140_4_6_oK6d',
 '1_2ecbplus_HUM15732980283919140_4_0_2CY9',
 '1_2ecbplus_HUM15732980283919140_4_30_GJev',
 '1_3ecbplus_HUM15732980283919140_3_1_jire',
 '1_3ecbplus_HUM15732980283919140_1_0_EnB3',
 '1_4ecbplus_HUM15732980283919140_6_25_iT3y',
 '1_4ecbplus_HUM15732980283919140_7_35_bjb9',
 '1_4ecbplus_HUM15732980283919140_1_0_9hKc',
 '1_4ecbplus_HUM15732980283919140_7_5_L4o6',
 '1_4ecbplus_HUM15732980283919140_6_4_Xonk',
 '1_4ecbplus_HUM15732980283919140_6_19_8RxJ',
 '1_5ecbplus_HUM15732980283919140_3_38_oT6c',
 '1_5ecbplus_HUM15732980283919140_1_2_A5Yd',
 '1_5ecbplus_HUM15732980283919140_3_0_b3os',
 '1_5ecbplus_HUM15732980283919140_3_8_hcwK',
 '1_6ecbplus_HUM15732980283919140_1_0_NBKC',
 '1_6ecbplus_HUM15732980283919140_3_19_WXav',
 '1_7ecbplus_HUM15732980283919140_3_5_GckS',
 '1_7ecbplus_HUM15732980283919140_3_25_KXGW',
 '1_7ecbplus_HUM15732980283919140_4_14_Wcty',
 '1_7ecbplus_HUM15732980283919140_1_0_oSbD',
 '1_7ecbplus_HUM15732980283919140_3_0_Ygkc',
 '1_8ecbplus_HUM15732980283919140_6_1_BpmY',
 '1_8ecbplus_HUM15732980283919140_4_1_nnww',
 '1_8ecbplus_HUM15732980283919140_1_0_D9NX',
 '1_8ecbplus_HUM15732980283919140_5_23_bEXP',
 '1_8ecbplus_HUM15732980283919140_7_0_nFZz',
 '1_8ecbplus_HUM15732980283919140_5_10_aQ8x',
 '1_9ecbplus_HUM15732980283919140_5_15_Jjz4',
 '1_9ecbplus_HUM15732980283919140_2_1_98VP',
 '1_9ecbplus_HUM15732980283919140_5_0_Y8Rz',
 '1_9ecbplus_HUM15732980283919140_4_4_QaXv',
 '1_9ecbplus_HUM15732980283919140_5_24_Bs5T',
 '1_9ecbplus_HUM15732980283919140_1_0_GMpg',
 '1_9ecbplus_HUM15732980283919140_2_13_oSaA',
 '1_10ecbplus_LOC15733316663614047_3_5_JDYc',
 '1_12ecbplus_LOC15733316663614047_3_31_9hMi',
 '1_12ecbplus_LOC15733316663614047_3_41_KpVU',
 '1_12ecbplus_LOC15733316663614047_1_9_ctRD',
 '1_13ecbplus_LOC15733316663614047_1_4_gLaF',
 '1_13ecbplus_LOC15733316663614047_3_5_gVwc',
 '1_15ecbplus_LOC15733316663614047_1_8_3Ubr',
 '1_15ecbplus_LOC15733316663614047_3_2_mDwu',
 '1_16ecbplus_LOC15733316663614047_1_5_bFGE',
 '1_16ecbplus_LOC15733316663614047_1_11_RZVy',
 '1_16ecbplus_LOC15733316663614047_3_6_gjAk',
 '1_16ecbplus_LOC15733316663614047_3_16_j6aL',
 '1_16ecbplus_LOC15733316663614047_3_27_L2Xp',
 '1_18ecbplus_LOC15733316663614047_4_22_RWcx',
 '1_18ecbplus_LOC15733316663614047_4_32_9ZVX',
 '1_18ecbplus_LOC15733316663614047_1_5_9Pb4',
 '1_19ecbplus_LOC15733316663614047_3_22_TSif',
 '1_21ecbplus_LOC15733316663614047_1_6_Rg3F',
 '1_21ecbplus_LOC15733316663614047_3_22_iahN',
 '1_21ecbplus_LOC15733316663614047_7_10_4JgE',
 '1_21ecbplus_LOC15733316663614047_3_6_JJTZ',
 '1_2ecbplus_LOC15733316663614047_2_6_ijPJ',
 '1_2ecbplus_LOC15733316663614047_4_10_FT9G',
 '1_2ecbplus_LOC15733316663614047_4_14_5vS2',
 '1_4ecbplus_LOC15733316663614047_1_4_ZsWC',
 '1_4ecbplus_LOC15733316663614047_6_9_HUC2',
 '1_4ecbplus_LOC15733316663614047_7_9_J8Hk',
 '1_4ecbplus_LOC15733316663614047_7_19_Lkjh',
 '1_5ecbplus_LOC15733316663614047_3_12_dZRg',
 '1_5ecbplus_LOC15733316663614047_1_6_jwNH',
 '1_5ecbplus_LOC15733316663614047_3_21_7ugk',
 '1_7ecbplus_LOC15733316663614047_3_14_jkvC',
 '1_7ecbplus_LOC15733316663614047_4_21_AUpR',
 '1_7ecbplus_LOC15733316663614047_3_8_6Yr5',
 '1_8ecbplus_LOC15733316663614047_6_22_EXWR',
 '1_8ecbplus_LOC15733316663614047_5_15_Ugmg',
 '1_8ecbplus_LOC15733316663614047_5_25_YsoC',
 '1_9ecbplus_LOC15733316663614047_5_20_AD6a',
 '1_9ecbplus_LOC15733316663614047_5_4_k3Da',
 '1_9ecbplus_LOC15733316663614047_2_5_CchY',
 '1_11ecbplus_HUM15743207473194727_2_22_5UgX',
 '1_11ecbplus_HUM15743207473194727_1_13_cJ5U',
 '1_19ecbplus_HUM15743207473194727_1_9_PWNQ',
 '1_1ecbplus_HUM15743207473194727_5_3_WGRt',
 '1_8ecbplus_HUM15743207473194727_4_7_86Yi',
 '1_8ecbplus_HUM15743207473194727_1_5_eDjW',
 '1_9ecbplus_HUM15743207473194727_4_10_6EeN',
 '1_9ecbplus_HUM15743207473194727_1_7_Wwe3',
 '1_9ecbplus_HUM15743207473194727_4_9_gdvm',
 '1_11ecbplus_HUM15997956240704274_5_26_MaLB',
 '1_11ecbplus_HUM15997945305247518_5_23_BdaX',
 '1_11ecbplus_TIM15992419152288715_2_15_Hcz4',
 '1_11ecbplus_TIM15992419152288715_5_10_8JLU',
 '1_14ecbplus_TIM15992419152288715_4_15_KTmS',
 '1_8ecbplus_TIM15992419152288715_7_7_TpTv',
 '1_12ecbplus_HUM15733182573500964_3_19_DdSD',
 '1_8ecbplus_HUM15733182573500964_6_31_L5jJ',
 '1_12ecbplus_HUM15986365101070461_3_14_3VAm',
 '1_18ecbplus_HUM15986365101070461_4_12_H2so',
 '1_7ecbplus_HUM15986365101070461_4_9_h36i',
 '1_8ecbplus_HUM15986365101070461_5_3_BXEJ',
 '1_4ecbplus_NON15988299424186214_7_36_2U3k',
 '1_12ecbplus_HUM15733047695318433_3_24_5xh5',
 '1_13ecbplus_HUM15733047695318433_1_12_egDr',
 '1_18ecbplus_HUM15733047695318433_4_1_2fm8',
 '1_21ecbplus_HUM15733047695318433_7_12_hq9X',
 '1_21ecbplus_HUM15733047695318433_1_0_cYxw',
 '1_2ecbplus_HUM15733047695318433_2_0_Q3PB',
 '1_2ecbplus_HUM15733047695318433_4_2_XYG3',
 '1_5ecbplus_HUM15733047695318433_1_0_iQrU',
 '1_5ecbplus_HUM15733047695318433_3_4_Unwh',
 '1_7ecbplus_HUM15733047695318433_4_0_WqKh',
 '1_7ecbplus_HUM15733047695318433_3_2_6US5',
 '1_8ecbplus_HUM15733047695318433_5_0_YXmJ',
 '1_13ecbplus_TIM15737493546220407_3_27_Kxzo',
 '1_18ecbplus_TIM16002615815900831_3_3_YCdU',
 '1_19ecbplus_TIM16002615815900831_3_30_fgbu',
 '1_18ecbplus_HUM15986292916798586_4_35_C6jQ',
 '1_19ecbplus_HUM15986292916798586_4_11_cQqM',
 '1_7ecbplus_HUM15986292916798586_4_32_h7bV',
 '1_18ecbplus_HUM16026605402957446_4_25_NauA',
 '1_15ecbplus_HUM15829977106103480_3_32_CWs7',
 '1_20ecbplus_HUM15829977106103480_4_23_JrD7',
 '1_8ecbplus_HUM15829977106103480_7_10_g93v',
 '1_9ecbplus_HUM15829977106103480_4_0_RrRv',
 '1_7ecbplus_HUM16069777087388471_3_22_gfDK',
 '1_14ecbplus_HUM16069832214901832_4_31_eDk3',
 '1_4ecbplus_TIM15988436785990721_7_11_94cB',
 '1_14ecbplus_HUM16069824318674606_1_11_H8Bq',
 '1_14ecbplus_HUM16069738500985838_4_34_C5sK',
 '1_15ecbplus_TIM15830333309896982_3_17_CCE5',
 '1_2ecbplus_TIM15830333309896982_4_4_kQcM',
 '1_5ecbplus_TIM15830333309896982_3_6_fwww',
 '1_7ecbplus_TIM15830333309896982_3_10_hhGy',
 '1_9ecbplus_TIM15830333309896982_5_7_eZPh',
 '1_9ecbplus_TIM15830333309896982_2_10_PCJW',
 '1_15ecbplus_Singleton_TIMeTmXXQw_3_10_irhT',
 '1_17ecbplus_TIM15734406543689590_4_0_FwJX',
 '1_6ecbplus_TIM15734406543689590_3_0_UvCe',
 '1_18ecbplus_Singleton_ACTnMLqxck_4_1_Pkj9',
 '1_19ecbplus_HUM15733138691810284_4_6_ZWcA',
 '1_21ecbplus_HUM15733138691810284_7_2_EmRo',
 '1_21ecbplus_HUM15733138691810284_7_0_kZer',
 '1_4ecbplus_TIM15988411783047999_6_16_PVFS',
 '1_4ecbplus_TIM15988411783047999_1_8_EKh5',
 '1_4ecbplus_TIM15988411783047999_7_15_Mrgi',
 '1_8ecbplus_TIM15988411783047999_6_25_KsLo',
 '1_8ecbplus_TIM15988411783047999_5_26_jJUi',
 '1_19ecbplus_HUMnab62eQqrg6u3X9ie_1_9_GGFK',
 '1_19ecbplus_TIM16071649504105255_3_14_XXdN',
 '1_1ecbplus_TIM15737524562357093_4_17_9nB3',
 '1_1ecbplus_HUM15736997945923117_4_3_6tdM',
 '1_1ecbplus_HUM15737056436705907_4_13_8p35',
 '1_1ecbplus_LOC15737144640543698_1_8_ZEet',
 '1_1ecbplus_LOC15737144640543698_4_24_eFZS',
 '1_1ecbplus_LOC15737144640543698_4_22_DcBZ',
 '1_1ecbplus_LOC15737144640543698_3_12_5kEo',
 '1_20ecbplus_LOC15737144640543698_4_10_nccL',
 '1_20ecbplus_LOC15737144640543698_4_16_4D52',
 '1_20ecbplus_LOC15737144640543698_1_11_KtYB',
 '1_3ecbplus_LOC15737144640543698_3_10_RMUA',
 '1_3ecbplus_LOC15737144640543698_1_13_BZze',
 '1_1ecbplus_HUM15737106999434470_4_1_MaaJ',
 '1_1ecbplus_HUM15736969418212999_3_21_CmTJ',
 '1_1ecbplus_HUM15736969418212999_4_10_FWzH',
 '1_1ecbplus_Singleton_ACTEjxiJV5_4_8_7JWu',
 '1_1ecbplus_Singleton_ACTMajunhB_5_3_jSMP',
 '1_20ecbplus_TIM15987171346344118_3_17_Vmdb',
 '1_21ecbplus_LOC15733332758669653_7_23_R49T',
 '1_21ecbplus_TIM15733571937310977_7_14_7z9E',
 '1_2ecbplus_HUM15830027488237317_4_28_dDXV',
 '1_5ecbplus_HUM15830027488237317_3_35_jwBZ',
 '1_7ecbplus_LOC15986415595839818_1_4_5Mai',
 '1_2ecbplus_Singleton_ACT56t93Tk_4_18_fQBS',
 '1_2ecbplus_Singleton_HUMnSR8K9M_4_17_2XmH',

In [7]:
import pandas as pd

In [3]:
cdcr_test.mentions[0].topic_id

KeyError: 0

In [28]:
df=pd.DataFrame(columns=["mention_id","source_path","topic_id","type"])


for mention in cdcr_test.mentions:
    new_row = {"mention_id":mention.mention_id,"source_path":mention.source_path,"topic_id":mention.topic_id,"type":mention.type}
    df = df.append(new_row, ignore_index=True)

C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
C:\Users\Sergio\AppData\Local\Temp\ipykernel_24320\2237806938.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)

In [29]:
repeated_mentions = df.mention_id.value_counts().reset_index().query("mention_id>1")["index"].to_list()

In [30]:
repeated_mentions

['34_7ecbplus_HUM17634109609806079_1_23_44tn',
 '34_13ecb_Singleton_ACTdJoWmRA_1_0_C5rm',
 '34_12ecb_Singleton_HUMTRY4667_1_18_XNmV',
 '34_12ecb_Singleton_HUMbeMLsNz_3_9_fRtP',
 '34_12ecb_Singleton_NEGVcXeeyw_2_4_C9rd',
 '34_13ecb_Singleton_ACTdnQavC8_1_30_DeRw',
 '34_13ecb_Singleton_ACTbrC7a6c_1_24_gzjy',
 '34_13ecb_Singleton_ACTGNsMdEJ_1_35_CGRU',
 '34_13ecb_Singleton_HUMexD9eja_0_10_3tcn',
 '34_14ecb_Singleton_ACTZ3Sz6Kd_0_21_J58S',
 '34_13ecb_Singleton_HUMR7zgkEY_1_6_g4Mw',
 '34_13ecb_Singleton_LOC7TvewqF_1_25_KEqZ',
 '34_13ecb_Singleton_NONB7Qk8Td_0_11_P7FE',
 '34_13ecb_Singleton_NON2SmGjxp_0_14_nrXC',
 '34_13ecb_Singleton_NON7VQ9vMv_1_27_2aXr',
 '34_13ecb_Singleton_NONnGV6p57_1_31_NoDf',
 '34_12ecb_Singleton_ACT2iUoZBg_2_11_VTkd',
 '34_12ecb_Singleton_ACTkt84hUM_0_22_oRH7',
 '34_12ecb_Singleton_ACTXPPMi33_0_24_5yhR',
 '34_12ecb_Singleton_ACTmmzJP6E_2_21_DzGJ',
 '34_12ecb_Singleton_ACTknbG3Ch_2_7_4Fkd',
 '34_12ecb_Singleton_ACTb6Hh7go_2_19_9yKr',
 '34_11ecb_Singleton_LOCM5xEpKV_1_29_cjzu',
 '34_11ecb_Singleton_LOCLQ9nTqB_1_27_9XSq',
 '34_11ecb_Singleton_HUM8htYGE4_1_26_BoQF',
 '34_11ecb_Singleton_HUMZH9LeQy_0_28_eMYt',
 '34_11ecb_Singleton_HUM6hb94qp_1_13_ZuMy',
 '34_11ecb_Singleton_ACTGseh2St_1_19_nqmU',
 '34_10ecb_Singleton_TIMBQvMJSF_6_21_5B4v',
 '34_10ecb_Singleton_TIMCCZRiZQ_0_2_GieS',
 '34_10ecb_Singleton_TIMHT9reu6_6_25_gno2',
 '34_10ecb_Singleton_NONVARTp8B_6_17_CFGd',
 '34_10ecb_Singleton_NONexDNJig_4_17_SaRS',
 '34_14ecb_Singleton_ACTC83PipK_0_17_9Khf',
 '34_14ecb_Singleton_ACT3k4EkGk_0_4_UdVW',
 '34_10ecb_Singleton_NEGbU8ob27_4_3_4EBA',
 '34_16ecb_Singleton_NON5Se6xcj_1_19_mCjd',
 '34_16ecb_Singleton_ACTWHnK56w_1_37_XQdn',
 '34_16ecb_Singleton_ACThPdrKJP_0_14_VzAt',
 '34_16ecb_Singleton_ACTMtAzadY_2_10_9NPn',
 '34_16ecb_Singleton_ACToQELBfu_2_27_3WzF',
 '34_16ecb_Singleton_HUMXGpPKuU_2_23_RXfN',
 '34_16ecb_Singleton_HUM9DAAAMg_2_7_2RKC',
 '34_1ecb_Singleton_ACT5xQZLDC_0_18_JcHC',
 '34_14ecb_Singleton_ACTMqeuye5_0_32_75pQ',
 '34_2ecb_Singleton_ACTLWJUAYc_0_5_TvLj',
 '34_2ecb_Singleton_ACTKMZcB3Q_0_38_EhQ9',
 '34_2ecb_Singleton_ACTdpynsgG_0_10_7nVW',
 '34_2ecb_Singleton_ACTcfU8CXx_0_16_gRQB',
 '34_2ecb_Singleton_ACT7UpNNek_0_14_6kW2',
 '34_2ecb_Singleton_HUMMULu5xP_0_13_HVpc',
 '34_16ecb_Singleton_ACTQtxjzJs_2_25_N4Qy',
 '34_16ecb_Singleton_ACT6SR8fB3_1_33_6KnM',
 '34_16ecb_Singleton_ACToH9ZYDs_1_17_beWd',
 '34_8ecb_TIM17636976013891213_0_32_5rEJ',
 '34_7ecb_TIM17636976013891213_0_27_dxZr',
 '34_1ecb_TIM17636976013891213_0_29_huQu',
 '34_16ecb_TIM17636976013891213_0_23_BqTN',
 '34_15ecb_Singleton_HUMFgR2TY7_0_46_56qT',
 '34_15ecb_Singleton_ACTGDjjUSf_0_44_gBk9',
 '34_15ecb_Singleton_ACT2nVNydJ_0_15_cfGH',
 '34_15ecb_Singleton_ACTCsDDBPj_0_41_eBkC',
 '34_15ecb_Singleton_ACTcbDBDWV_0_36_gfrR',
 '34_15ecb_Singleton_ACTRSHsUeE_0_34_DUb4',
 '34_15ecb_Singleton_ACTKufo5ai_0_39_K4m2',
 '34_15ecb_Singleton_ACTC3MbwQV_0_28_iNJp',
 '34_14ecb_Singleton_TIMikASmvA_0_33_kymT',
 '34_14ecb_Singleton_NEG3CQEhWk_0_29_7SbN',
 '34_10ecb_Singleton_NON2uCggsV_4_11_jhKU',
 '34_10ecb_Singleton_NEGVZj6mJj_4_9_h3kK',
 '34_2ecb_Singleton_HUMXhaMG5b_0_40_THiU',
 '34_9ecb_HUM17634109609806079_0_29_dpVi',
 '34_2ecb_HUM17634109609806079_0_42_PEsx',
 '34_3ecb_HUM17634109609806079_0_16_kNbr',
 '34_4ecb_HUM17634109609806079_0_20_BQWZ',
 '34_6ecb_HUM17634109609806079_1_16_hA6m',
 '34_7ecb_HUM17634109609806079_0_22_AQWn',
 '34_8ecb_HUM17634109609806079_0_24_LaQB',
 '34_12ecb_HUM16070611587969207_3_0_XjKi',
 '34_9ecb_HUM16070611587969207_2_1_DjoH',
 '34_1ecb_HUM16070611587969207_0_26_BxeD',
 '34_3ecb_HUM16070611587969207_0_13_Vz7a',
 '34_6ecb_HUM16070611587969207_1_19_bNSM',
 '34_6ecb_HUM16070611587969207_1_0_D26Z',
 '34_6ecb_HUM16070611587969207_0_0_fp44',
 '34_7ecb_HUM16070611587969207_0_25_gSFW',
 '34_1ecb_HUM17634109609806079_0_22_58WL',
 '34_16ecb_HUM17634109609806079_0_15_DfKU',
 '34_16ecb_HUM17634109609806079_1_21_4QMG',
 '34_15ecb_HUM17634109609806079_0_21_jzCw',
 '34_14ecb_HUM17634109609806079_0_7_ndaY',
 '34_13ecb_HUM17634109609806079_0_7_bYLF',
 '34_12ecb_HUM17634109609806079_1_24_Lk6Y',
 '34_12ecb_HUM17634109609806079_0_19_mjpn',
 '34_11ecb_HUM17634109609806079_0_19_du4U',
 '34_10ecb_HUM17634109609806079_4_31_ZUyK',
 '34_9ecb_HUM17634097626820205_2_14_hzYJ',
 '34_9ecb_HUM17634097626820205_2_4_i2Yv',
 '34_9ecb_HUM17634097626820205_0_3_QXit',
 '34_8ecb_HUM17634097626820205_0_2_hRGB',
 '34_7ecb_HUM17634097626820205_0_7_4wRs',
 '34_6ecb_HUM17634097626820205_1_9_9ej4',
 '34_6ecb_HUM17634097626820205_0_6_QuPC',
 '34_9ecb_HUM16070611587969207_2_9_W5xP',
 '34_10ecb_HUM17209079221902940_6_12_cnLB',
 '34_10ecb_Singleton_ACThyWaPMs_0_1_Wxyf',
 '34_13ecb_UNKFCk4Hp7b6PvhJpUQi_1_22_QucE',
 '34_11ecb_UNKFCk4Hp7b6PvhJpUQi_1_24_9rHC',
 '34_12ecb_UNKFCk4Hp7b6PvhJpUQi_1_2_UGuC',
 '34_12ecb_UNKFCk4Hp7b6PvhJpUQi_2_10_YTHf',
 '34_12ecb_UNKFCk4Hp7b6PvhJpUQi_1_17_Quv3',
 '34_12ecb_UNKFCk4Hp7b6PvhJpUQi_0_12_g5My',
 '34_13ecb_UNKFCk4Hp7b6PvhJpUQi_1_21_A3sj',
 '34_16ecb_UNKFCk4Hp7b6PvhJpUQi_1_28_7FJ4',
 '34_10ecb_HUM17209079221902940_0_4_7f7b',
 '34_16ecb_UNKFCk4Hp7b6PvhJpUQi_0_21_NKZy',
 '34_16ecb_UNKFCk4Hp7b6PvhJpUQi_0_22_GPXh',
 '34_16ecb_UNKFCk4Hp7b6PvhJpUQi_1_26_aEcw',
 '34_9ecb_UNKFCk4Hp7b6PvhJpUQi_2_31_MCx5',
 '34_9ecb_UNKFCk4Hp7b6PvhJpUQi_2_32_eY6q',
 '34_10ecb_Singleton_ACToWDQKMC_6_13_JQUY',
 '34_11ecb_UNKFCk4Hp7b6PvhJpUQi_1_22_8HV3',
 '34_11ecb_UNKFCk4Hp7b6PvhJpUQi_1_10_8kjE',
 '34_11ecb_UNKFCk4Hp7b6PvhJpUQi_0_26_ZuyM',
 '34_10ecb_UNKFCk4Hp7b6PvhJpUQi_0_0_EPXH',
 '34_10ecb_UNKFCk4Hp7b6PvhJpUQi_4_5_72N2',
 '34_9ecb_HUM17209079221902940_0_12_XiJS',
 '34_7ecb_HUM17209079221902940_0_2_62J3',
 '34_4ecb_HUM17209079221902940_0_3_SKmD',
 '34_3ecb_HUM17209079221902940_0_2_NnDK',
 '34_2ecb_HUM17209079221902940_0_19_65Jx',
 '34_16ecb_HUM17209079221902940_1_35_Hm4F',
 '34_16ecb_HUM17209079221902940_0_1_HCxH',
 '34_14ecb_HUM17209079221902940_0_1_kRnP',
 '34_13ecb_HUM17209079221902940_0_0_H7fh',
 '34_12ecb_HUM17209079221902940_0_0_hw5n',
 '34_11ecb_HUM17209079221902940_0_23_NnQP',
 '34_10ecb_HUM17209079221902940_6_4_Z5Pb',
 '34_2ecb_Singleton_HUMTGGkBkZ_0_7_hvBF',
 '34_3ecb_Singleton_ACTBfFefZu_0_19_oSAY',
 '34_11ecbplus_HUM17634086926494905_3_24_cDYE',
 '34_6ecbplus_HUM17634109609806079_3_12_ZXfT',
 '34_9ecbplus_HUM17634109609806079_1_6_8WF9',
 '34_9ecbplus_HUM17634109609806079_3_17_3uow',
 '34_8ecbplus_HUM17634109609806079_2_0_PiLi',
 '34_11ecbplus_HUM17634086926494905_1_0_HDNM',
 '34_7ecbplus_HUM17634109609806079_4_28_GpAP',
 '34_6ecbplus_HUM17634109609806079_1_9_2XBa',
 '34_5ecbplus_HUM17634109609806079_1_9_mkmn',
 '34_1ecbplus_HUM17634109609806079_5_15_oUA3',
 '34_5ecbplus_HUM17634109609806079_4_20_BGRZ',
 '34_4ecbplus_HUM17634109609806079_3_9_N5Bk',
 '34_4ecbplus_HUM17634109609806079_1_14_drdi',
 '34_3ecbplus_HUM17634109609806079_3_28_ZRxQ',
 '34_2ecbplus_HUM17634109609806079_3_7_i8XG',
 '34_2ecbplus_HUM17634109609806079_1_7_d3Qy',
 '34_9ecbplus_HUM17634109609806079_5_16_LbuY',
 '34_9ecbplus_HUM17634109609806079_5_24_En7s',
 '34_10ecbplus_HUM17209079221902940_1_0_WucS',
 '34_11ecbplus_HUM17209079221902940_3_1_ibfa',
 '34_12ecbplus_HUM17209079221902940_4_7_6uDV',
 '34_12ecbplus_HUM17209079221902940_4_4_PkRc',
 '34_1ecbplus_HUM17209079221902940_5_3_9DVg',
 '34_1ecbplus_HUM17209079221902940_5_6_QVd7',
 '34_1ecbplus_HUM17209079221902940_4_1_BCP5',
 '34_2ecbplus_HUM17209079221902940_3_1_Vzcu',
 '34_2ecbplus_HUM17209079221902940_3_3_27YB',
 '34_3ecbplus_HUM17209079221902940_3_4_5UP4',
 '34_3ecbplus_HUM17209079221902940_3_1_bUwk',
 '34_4ecbplus_HUM17209079221902940_3_1_ZfmJ',
 '34_4ecbplus_HUM17209079221902940_1_8_moqe',
 '34_6ecbplus_HUM17209079221902940_3_1_f3w5',
 '34_6ecbplus_HUM17209079221902940_1_0_ZTJo',
 '34_1ecbplus_HUM17634109609806079_4_5_A7Db',
 '34_12ecbplus_HUM17634109609806079_1_9_kV5g',
 '34_9ecbplus_HUM17209079221902940_5_5_dZS2',
 '34_3ecbplus_HUM17634086926494905_3_14_LMB2',
 '34_6ecbplus_HUM17634086926494905_3_6_QK4C',
 '34_6ecbplus_HUM17634086926494905_1_2_ankY',
 '34_5ecbplus_HUM17634086926494905_1_4_W7os',
 '34_5ecbplus_HUM17634086926494905_4_7_fkU3',
 '34_4ecbplus_HUM17634086926494905_3_4_DFV2',
 '34_4ecbplus_HUM17634086926494905_1_11_aegQ',
 '34_3ecbplus_HUM17634086926494905_3_13_SqDw',
 '34_12ecbplus_HUM17634109609806079_4_26_Kmi5',
 '34_3ecbplus_HUM17634086926494905_3_7_ZjR3',
 '34_2ecbplus_HUM17634086926494905_1_0_Y9Jd',
 '34_2ecbplus_HUM17634086926494905_3_14_E5gr',
 '34_1ecbplus_HUM17634086926494905_5_10_N6jG',
 '34_12ecbplus_HUM17634086926494905_4_10_iLo8',
 '34_12ecbplus_HUM17634086926494905_1_0_D87W',
 '34_7ecbplus_HUM17634086926494905_4_9_YkyQ',
 '34_7ecbplus_HUM17634086926494905_4_7_cgUE',
 '34_7ecbplus_HUM17634086926494905_1_0_CKq2',
 '34_8ecbplus_HUM17634086926494905_2_3_gtkc',
 '34_9ecbplus_HUM17634086926494905_5_11_iJQS',
 '34_9ecbplus_HUM17634086926494905_1_2_J762',
 '34_9ecbplus_HUM17634086926494905_3_10_cjDo',
 '34_11ecbplus_TIM17634315013134476_3_8_TASy',
 '34_12ecbplus_TIM17634315013134476_4_0_E5cf',
 '34_1ecbplus_TIM17634315013134476_5_0_ix6z',
 '34_2ecbplus_TIM17634315013134476_3_19_krjj',
 '34_3ecbplus_TIM17634315013134476_3_43_4Xyx',
 '34_4ecbplus_TIM17634315013134476_3_20_TkNE',
 '34_9ecbplus_TIM17634315013134476_5_2_ByB5',
 '34_10ecbplus_HUM17634109609806079_1_3_N9Tc',
 '34_11ecbplus_HUM17634109609806079_1_2_2DoW',
 '34_11ecbplus_HUM17634109609806079_3_17_m2we',
 '34_9ecbplus_HUM17209079221902940_5_7_kL6z',
 '34_9ecbplus_HUM17209079221902940_1_0_3ozz',
 '34_3ecb_Singleton_ACTXLm3M68_0_0_bP3m',
 '34_8ecb_Singleton_ACTVULS55k_0_31_P6Kq',
 '34_6ecb_Singleton_ACTftyum27_1_31_TPr9',
 '34_6ecb_Singleton_HUMT9kyijV_1_23_3z2Q',
 '34_6ecb_Singleton_TIMg2Wfxoe_0_4_DS9F',
 '34_7ecb_Singleton_ACTFVbNd6w_0_17_HczV',
 '34_7ecb_Singleton_ACTZaKeWft_0_26_XmKb',
 '34_8ecb_Singleton_ACTQDD74rA_0_21_9bWu',
 '34_8ecb_Singleton_HUM4N2UiEZ_0_11_komq',
 '34_9ecb_Singleton_ACTUvz3M5e_2_12_k79x',
 '34_8ecb_Singleton_HUMQguwAJB_0_14_ThZx',
 '34_8ecb_Singleton_HUMjAtNWAB_0_30_X6uB',
 '34_9ecb_Singleton_ACTKmBMKrz_2_25_LVTg',
 '34_9ecb_Singleton_ACT3tbsDgd_2_2_bbkS',
 '34_9ecb_Singleton_ACTkft3qjZ_0_17_hy5x',
 '34_9ecb_Singleton_ACTWwQLmrb_0_31_FiSy',
 '34_6ecb_Singleton_ACT9z45S9Z_1_37_jtv7',
 '34_6ecb_Singleton_ACTBH5bVoR_1_36_M6mK',
 '34_6ecb_Singleton_ACTfuDa7Cf_1_21_8smy',
 '34_6ecb_Singleton_ACT8QVukU5_1_40_armQ',
 '34_6ecb_Singleton_ACTmizht2J_1_7_C4ui',
 '34_6ecb_Singleton_ACT7gbRxmx_1_41_PETX',
 '34_6ecb_Singleton_ACTadnF2eG_1_32_6NjA',
 '34_6ecb_NON17640632758867156_1_29_U3gk',
 '34_4ecb_Singleton_HUMPtpnxb9_0_27_fqga',
 '34_4ecb_Singleton_ACTV66AN4s_0_33_gaiC',
 '34_4ecb_Singleton_ACTZb8nnq9_0_0_JWjn',
 '34_4ecb_Singleton_ACTPTBCLXb_0_17_amkt',
 '34_4ecb_Singleton_ACTmhmTiPm_0_29_Xxsf',
 '34_4ecb_Singleton_ACTbCdSj2N_0_25_S4h4',
 '34_4ecb_Singleton_ACTcT42wTr_0_22_CmvM',
 '34_3ecb_Singleton_LOC6BsfCVK_0_10_mqr4',
 '34_3ecb_Singleton_ACTe4rdnVh_0_24_jsa8',
 '34_9ecb_Singleton_ACTGEvmNxX_0_28_nzKT',
 '34_9ecb_Singleton_ACTi4ygeZg_2_20_5fFy',
 '34_9ecbplus_HUM17209079221902940_3_1_ZdUd',
 '34_1ecbplus_Singleton_HUMH2ScTGJ_5_18_nAs5',
 '34_4ecbplus_Singleton_HUMLiDehhD_1_1_jRYN',
 '34_3ecbplus_Singleton_ACT33jGvkz_3_15_Vebw',
 '34_3ecbplus_LOC17634169860736271_3_16_KEeG',
 '34_4ecbplus_LOC17634300680503542_3_17_7SYt',
 '34_3ecbplus_LOC17634300680503542_3_37_XayC',
 '34_2ecbplus_LOC17634300680503542_3_20_Jq93',
 '34_1ecbplus_Singleton_ACTBE2a2Ht_5_7_FPWR',
 '34_9ecb_Singleton_ACTHksQW8N_2_21_Ergr',
 '34_12ecbplus_Singleton_HUMmycvGpt_4_18_LafB',
 '34_9ecbplus_LOC17634180095063192_3_11_mbUj',
 '34_12ecbplus_LOC17634180095063192_4_22_fHgw',
 '34_11ecbplus_Singleton_ACTfgo3e8P_3_5_Y8vN',
 '34_11ecbplus_Singleton_ACTD7yLrkd_3_3_Q6bP',
 '34_9ecbplus_HUM17209079221902940_3_6_JFAj',
 '34_5ecbplus_HUM17636109378642046_1_0_DKTN',
 '34_5ecbplus_HUM17636109378642046_4_1_7LVD',
 '34_5ecbplus_Singleton_ACTgBB6DAD_1_1_QXhD',
 '34_5ecbplus_Singleton_ACT8UKeuvA_4_5_MzeJ',
 '34_7ecbplus_HUMYqQ7sjHRUtpeAVnpS_4_1_3JYk',
 '34_7ecbplus_Singleton_ACTYdgKGRF_4_5_hvQy',
 '34_9ecbplus_Singleton_ACTFNe8TZy_5_8_CDxh',
 '34_9ecbplus_Singleton_ACTfL3TrUS_5_6_VHcU',
 '34_9ecbplus_Singleton_ACTNfgNBgM_5_24_4KL3',
 '34_9ecbplus_Singleton_HUMHGCxydL_5_20_2zfn',
 '34_10ecbplus_HUM17634086926494905_1_6_MWws',
 '34_9ecb_Singleton_NON9ZFJoC2_2_24_YEaq',
 '34_9ecb_Singleton_NEGesPErn2_2_19_Gsua',
 '34_9ecb_Singleton_HUME3GsgWR_0_23_dp5m',
 '34_9ecb_Singleton_HUMVibCjf3_0_34_btuJ',
 '34_9ecb_Singleton_ACTf3CPxbQ_0_36_TNLB',
 '34_9ecb_Singleton_ACTY4JYntR_0_21_H9ZW',
 '34_4ecb_HUM17634097626820205_0_12_9TrM',
 '34_3ecb_HUM17634097626820205_0_6_YZ8v',
 '34_2ecb_HUM17634097626820205_0_23_huDG',
 '34_10ecbplus_ACT17634128576760407_1_1_687u',
 '34_5ecbplus_ACT17634128576760407_1_2_d8E3',
 '34_4ecbplus_ACT17634128576760407_3_3_2tCB',
 '34_4ecbplus_ACT17634128576760407_1_10_kkHH',
 '34_3ecbplus_ACT17634128576760407_3_5_3Edg',
 '34_2ecbplus_ACT17634128576760407_1_5_knbm',
 '34_2ecbplus_ACT17634128576760407_3_4_V9hy',
 '34_1ecbplus_ACT17634128576760407_5_9_BsmG',
 '34_1ecbplus_ACT17634128576760407_4_3_jZRm',
 '34_12ecbplus_ACT17634128576760407_1_6_9x3q',
 '34_12ecbplus_ACT17634128576760407_4_9_eVWc',
 '34_11ecbplus_ACT17634128576760407_3_15_eUX8',
 '34_11ecbplus_ACT17634128576760407_1_8_KvEB',
 '34_9ecbplus_ACT17634157508289507_5_3_Xm9S',
 '34_6ecbplus_ACT17634128576760407_3_3_6opz',
 '34_9ecbplus_ACT17634157508289507_3_4_3jyf',
 '34_4ecbplus_ACT17634157508289507_3_19_ag9U',
 '34_3ecbplus_ACT17634157508289507_3_3_DkWg',
 '34_3ecbplus_ACT17634157508289507_3_36_mgth',
 '34_2ecbplus_ACT17634157508289507_3_2_RqDN',
 '34_1ecbplus_ACT17634157508289507_5_5_B8nh',
 '34_1ecbplus_ACT17634157508289507_4_2_MrEh',
 '34_12ecbplus_ACT17634157508289507_4_5_kQNL',
 '34_11ecbplus_ACT17634157508289507_3_13_SyBW',
 '34_9ecb_ACT17640665046565698_2_16_8mox',
 '34_6ecb_ACT17640665046565698_1_25_FmY7',
 '34_6ecb_ACT17640330135219317_0_3_dkTY',
 '34_5ecbplus_ACT17634128576760407_4_16_gf86',
 '34_6ecbplus_ACT17634128576760407_1_1_2f8k',
 '34_1ecb_ACT17640330135219317_0_28_aMZV',
 '34_10ecb_HUM17634097626820205_0_11_aXpw',
 '34_1ecb_HUM17634097626820205_0_7_WtWB',
 '34_10ecb_HUM17212524027211372_4_27_HzXa',
 '34_12ecb_HUM17212524027211372_0_15_2Yb5',
 '34_12ecb_HUM17212524027211372_1_10_W7Zp',
 '34_16ecb_HUM17212524027211372_1_40_h59K',
 '34_16ecb_HUM17212524027211372_1_5_K4gb',
 '34_1ecb_HUM17212524027211372_0_15_avdX',
 '34_6ecb_HUM17212524027211372_0_13_4XZ5',
 '34_6ecb_HUM17212524027211372_1_44_gVTf',
 '34_9ecb_HUM17212524027211372_2_28_NNG5',
 '34_10ecb_HUM17634097626820205_6_20_Xk2D',
 '34_10ecb_HUM17634097626820205_6_10_Z79z',
 '34_10ecb_HUM17634097626820205_4_0_GmWc',
 '34_7ecbplus_ACT17634128576760407_1_21_4Wq7',
 '34_10ecb_HUM17634097626820205_4_20_eT4h',
 '34_11ecb_HUM17634097626820205_1_0_cE92',
 '34_11ecb_HUM17634097626820205_0_0_a6q6',
 '34_12ecb_HUM17634097626820205_3_3_Phnp',
 '34_6ecbplus_ACT17635967637330797_1_7_gc38',
 '34_6ecbplus_ACT17635967637330797_3_11_fQRM',
 '34_5ecbplus_ACT17635967637330797_4_18_9oGb',
 '34_9ecbplus_ACT17634128576760407_3_8_WX5s',
 '34_9ecbplus_ACT17634128576760407_1_1_G6iT',
 '34_9ecbplus_ACT17634128576760407_5_10_4Xrx',
 '34_8ecbplus_ACT17634128576760407_2_2_NPT4',
 '34_7ecbplus_ACT17634128576760407_4_26_B575',
 '34_6ecb_ACT17640330135219317_1_2_YsRb',
 '34_12ecbplus_HUM17634086926494905_4_19_8s6A',
 '34_12ecb_ACT17640330135219317_3_2_Q5LF',
 '34_12ecb_HUM17634097626820205_2_1_jnW8',
 '34_13ecb_ACT17635941459366322_1_9_QKRq',
 '34_13ecb_ACT17635941459366322_0_3_aYTq',
 '34_12ecb_ACT17635941459366322_3_6_HcNx',
 '34_12ecb_ACT17635941459366322_0_3_Yhdr',
 '34_11ecb_ACT17635941459366322_0_15_43EU',
 '34_10ecb_ACT17635941459366322_4_24_hZCM',
 '34_10ecb_ACT17635941459366322_0_6_XdR2',
 '34_10ecb_ACT17635941459366322_6_9_beor',
 '34_12ecb_HUM17634097626820205_2_13_2ZNR',
 '34_12ecb_HUM17634097626820205_0_8_ev58',
 '34_12ecb_HUM17634097626820205_1_6_4anE',
 '34_12ecb_HUM17634097626820205_1_14_ncHE',
 '34_13ecb_HUM17634097626820205_1_19_Kd35',
 '34_16ecb_ACT17635941459366322_0_4_o3Pi',
 '34_13ecb_HUM17634097626820205_0_4_CFdJ',
 '34_13ecb_HUM17634097626820205_1_33_L2YB',
 '34_14ecb_HUM17634097626820205_0_13_iHbC',
 '34_15ecb_HUM17634097626820205_0_16_QJ7C',
 '34_15ecb_HUM17634097626820205_0_25_AqwS',
 '34_15ecb_HUM17634097626820205_0_0_dMi7',
 '34_16ecb_HUM17634097626820205_1_20_gQbm',
 '34_16ecb_HUM17634097626820205_1_9_24No',
 '34_16ecb_HUM17634097626820205_1_0_VLFX',
 '34_16ecb_HUM17634097626820205_2_12_CUeZ',
 '34_16ecb_HUM17634097626820205_0_10_AWf3',
 '34_13ecb_ACT17640348188037620_1_37_b3L9',
 '34_15ecb_ACT17635941459366322_0_18_hmEp',
 '34_14ecb_HUM17634097626820205_0_5_4Ksi',
 '34_16ecb_ACT17635941459366322_2_15_2qNT',
 '34_10ecb_ACT17640644449345164_0_8_cDdM',
 '34_11ecb_ACT17640348188037620_1_6_hrxn',
 '34_12ecb_ACT17640348188037620_2_14_gtfG',
 '34_1ecb_ACT17635941459366322_0_12_PhZ9',
 '34_6ecb_ACT17640644449345164_1_17_UxXT',
 '34_1ecb_ACT17640644449345164_0_20_dBUt',
 '34_16ecb_ACT17640644449345164_2_17_d99P',
 '34_16ecb_ACT17640644449345164_1_15_PbxY',
 '34_15ecb_ACT17640644449345164_0_31_NJkP',
 '34_14ecb_ACT17640644449345164_0_25_3SGt',
 '34_12ecb_ACT17640644449345164_2_16_f9pC',
 '34_11ecb_ACT17640644449345164_1_8_QFWC',
 '34_11ecb_ACT17640644449345164_0_17_jmN3',
 '34_16ecb_ACT17640644449345164_1_13_kP9D',
 '34_10ecb_ACT17640644449345164_4_35_CDQm',
 '34_7ecb_ACT17635941459366322_0_5_6i4D',
 '34_3ecb_ACT17635941459366322_0_5_9Hg3',
 '34_10ecb_ACT17636697918211092_4_14_hkfW',
 '34_2ecb_ACT17635941459366322_0_22_Z7QG',
 '34_6ecb_ACT17635941459366322_0_10_BkkP',
 '34_6ecb_ACT17635941459366322_1_13_4FUD',
 '34_8ecb_ACT17635941459366322_0_19_CNJj',
 '34_9ecb_ACT17635941459366322_2_6_oC66',
 '34_9ecb_ACT17635941459366322_0_2_jfsG',
 '34_10ecb_NEG17640364597903956_0_16_jCRz',
 '34_4ecb_ACT17635941459366322_0_6_WDGP']

In [31]:
df.query("mention_id==@repeated_mentions")[["source_path","topic_id","type"]].drop_duplicates()

                                       source_path topic_id    type
4960   ../CDCR/data/ECBplus-prep/output_data/train       34  entity
8470   ../CDCR/data/ECBplus-prep/output_data/train       34   event
10043    ../CDCR/data/ECBplus-prep/output_data/val       34  entity
11389    ../CDCR/data/ECBplus-prep/output_data/val       34   event

In [35]:
df.query("mention_id==@repeated_mentions").sample(10)

,mention_id,source_path,topic_id,type
10263,34_10ecbplus_HUM17634086926494905_1_6_MWws,../CDCR/data/ECBplus-prep/output_data/val,34,entity
5253,34_9ecbplus_HUM17209079221902940_3_1_ZdUd,../CDCR/data/ECBplus-prep/output_data/train,34,entity
8517,34_1ecbplus_ACT17634157508289507_5_5_B8nh,../CDCR/data/ECBplus-prep/output_data/train,34,event
11413,34_10ecb_ACT17640644449345164_0_8_cDdM,../CDCR/data/ECBplus-prep/output_data/val,34,event
5209,34_3ecbplus_TIM17634315013134476_3_43_4Xyx,../CDCR/data/ECBplus-prep/output_data/train,34,entity
10177,34_13ecb_Singleton_HUMR7zgkEY_1_6_g4Mw,../CDCR/data/ECBplus-prep/output_data/val,34,entity
10240,34_6ecb_Singleton_HUMT9kyijV_1_23_3z2Q,../CDCR/data/ECBplus-prep/output_data/val,34,entity
8529,34_1ecbplus_ACT17634128576760407_4_3_jZRm,../CDCR/data/ECBplus-prep/output_data/train,34,event
10047,34_16ecb_HUM17212524027211372_1_5_K4gb,../CDCR/data/ECBplus-prep/output_data/val,34,entity
10283,34_7ecbplus_HUM17634086926494905_1_0_CKq2,../CDCR/data/ECBplus-prep/output_data/val,34,entity

In [5]:
len(all_mentions)

15491

In [6]:
len(set(all_mentions))

15094

In [3]:
cdcr_test.sentences.keys()

dict_keys(['12/12ecb/1', '12/12ecb/10', '12/12ecb/11', '12/12ecb/12', '12/12ecb/13', '12/12ecb/14', '12/12ecb/15', '12/12ecb/16', '12/12ecb/17', '12/12ecb/18', '12/12ecb/19', '12/12ecb/2', '12/12ecb/3', '12/12ecb/4', '12/12ecb/5', '12/12ecb/6', '12/12ecb/7', '12/12ecb/8', '12/12ecb/9', '12/12ecbplus/1', '12/12ecbplus/10', '12/12ecbplus/11', '12/12ecbplus/2', '12/12ecbplus/3', '12/12ecbplus/4', '12/12ecbplus/5', '12/12ecbplus/6', '12/12ecbplus/7', '12/12ecbplus/8', '12/12ecbplus/9', '18/18ecb/1', '18/18ecb/10', '18/18ecb/11', '18/18ecb/12', '18/18ecb/13', '18/18ecb/14', '18/18ecb/15', '18/18ecb/16', '18/18ecb/2', '18/18ecb/3', '18/18ecb/4', '18/18ecb/5', '18/18ecb/6', '18/18ecb/7', '18/18ecb/8', '18/18ecb/9', '18/18ecbplus/1', '18/18ecbplus/10', '18/18ecbplus/11', '18/18ecbplus/2', '18/18ecbplus/3', '18/18ecbplus/4', '18/18ecbplus/5', '18/18ecbplus/6', '18/18ecbplus/7', '18/18ecbplus/8', '18/18ecbplus/9', '2/2ecb/1', '2/2ecb/11', '2/2ecb/2', '2/2ecb/3', '2/2ecb/4', '2/2ecb/5', '2/2ecb/6', '2/2ecb/7', '2/2ecb/8', '2/2ecb/9', '2/2ecbplus/1', '2/2ecbplus/10', '2/2ecbplus/11', '2/2ecbplus/2', '2/2ecbplus/3', '2/2ecbplus/4', '2/2ecbplus/5', '2/2ecbplus/6', '2/2ecbplus/7', '2/2ecbplus/8', '2/2ecbplus/9', '21/21ecb/1', '21/21ecb/10', '21/21ecb/11', '21/21ecb/12', '21/21ecb/2', '21/21ecb/3', '21/21ecb/4', '21/21ecb/5', '21/21ecb/6', '21/21ecb/7', '21/21ecb/8', '21/21ecb/9', '21/21ecbplus/1', '21/21ecbplus/10', '21/21ecbplus/11', '21/21ecbplus/12', '21/21ecbplus/13', '21/21ecbplus/14', '21/21ecbplus/2', '21/21ecbplus/3', '21/21ecbplus/4', '21/21ecbplus/5', '21/21ecbplus/6', '21/21ecbplus/7', '21/21ecbplus/8', '21/21ecbplus/9', '22/22ecb/1', '22/22ecb/2', '22/22ecb/3', '22/22ecb/4', '22/22ecb/5', '22/22ecb/6', '22/22ecb/7', '22/22ecb/8', '22/22ecb/9', '22/22ecbplus/1', '22/22ecbplus/10', '22/22ecbplus/11', '22/22ecbplus/12', '22/22ecbplus/13', '22/22ecbplus/14', '22/22ecbplus/2', '22/22ecbplus/3', '22/22ecbplus/4', '22/22ecbplus/5', '22/22ecbplus/6', '22/22ecbplus/7', '22/22ecbplus/8', '22/22ecbplus/9', '23/23ecb/1', '23/23ecb/10', '23/23ecb/2', '23/23ecb/3', '23/23ecb/4', '23/23ecb/5', '23/23ecb/6', '23/23ecb/7', '23/23ecb/8', '23/23ecb/9', '23/23ecbplus/1', '23/23ecbplus/10', '23/23ecbplus/11', '23/23ecbplus/2', '23/23ecbplus/3', '23/23ecbplus/4', '23/23ecbplus/5', '23/23ecbplus/6', '23/23ecbplus/7', '23/23ecbplus/8', '23/23ecbplus/9', '25/25ecb/1', '25/25ecb/10', '25/25ecb/11', '25/25ecb/12', '25/25ecb/13', '25/25ecb/14', '25/25ecb/15', '25/25ecb/2', '25/25ecb/3', '25/25ecb/4', '25/25ecb/5', '25/25ecb/6', '25/25ecb/7', '25/25ecb/8', '25/25ecb/9', '25/25ecbplus/10', '25/25ecbplus/11', '25/25ecbplus/13', '25/25ecbplus/14', '25/25ecbplus/15', '25/25ecbplus/3', '25/25ecbplus/5', '25/25ecbplus/6', '25/25ecbplus/7', '25/25ecbplus/8', '25/25ecbplus/9', '32/32ecb/1', '32/32ecb/2', '32/32ecb/3', '32/32ecb/4', '32/32ecb/5', '32/32ecb/6', '32/32ecb/7', '32/32ecb/8', '32/32ecbplus/1', '32/32ecbplus/10', '32/32ecbplus/11', '32/32ecbplus/2', '32/32ecbplus/3', '32/32ecbplus/4', '32/32ecbplus/5', '32/32ecbplus/6', '32/32ecbplus/7', '32/32ecbplus/8', '32/32ecbplus/9', '34/34ecb/1', '34/34ecb/10', '34/34ecb/11', '34/34ecb/12', '34/34ecb/13', '34/34ecb/14', '34/34ecb/15', '34/34ecb/16', '34/34ecb/2', '34/34ecb/3', '34/34ecb/4', '34/34ecb/5', '34/34ecb/6', '34/34ecb/7', '34/34ecb/8', '34/34ecb/9', '34/34ecbplus/1', '34/34ecbplus/10', '34/34ecbplus/11', '34/34ecbplus/12', '34/34ecbplus/2', '34/34ecbplus/3', '34/34ecbplus/4', '34/34ecbplus/5', '34/34ecbplus/6', '34/34ecbplus/7', '34/34ecbplus/8', '34/34ecbplus/9', '35/35ecb/1', '35/35ecb/10', '35/35ecb/2', '35/35ecb/3', '35/35ecb/4', '35/35ecb/5', '35/35ecb/6', '35/35ecb/7', '35/35ecb/8', '35/35ecb/9', '35/35ecbplus/1', '35/35ecbplus/10', '35/35ecbplus/11', '35/35ecbplus/2', '35/35ecbplus/3', '35/35ecbplus/4', '35/35ecbplus/5', '35/35ecbplus/6', '35/35ecbplus/7', '35/35ecbplus/8', '35/35ecbplus/9', '42/42ecb/1', '42/42ecb/10', '42/42ecb/11', '42/42ecb/12', '42/42ecb/13', '42/42ecb/2', '42/42ecb/3', '42/42ecb/4', '42/42ecb/5', '42/42ecb/6', '42/42ecb/7', '42/42ecb/8', '42/42ecb/9', '42/42ecbplus/1', '42/42ecbplus/10', '42/42ecbplus/2', '42/42ecbplus/3', '42/42ecbplus/4', '42/42ecbplus/5', '42/42ecbplus/6', '42/42ecbplus/7', '42/42ecbplus/8', '42/42ecbplus/9', '45/45ecb/1', '45/45ecb/2', '45/45ecb/3', '45/45ecb/4', '45/45ecb/5', '45/45ecb/6', '45/45ecb/7', '45/45ecb/8', '45/45ecbplus/1', '45/45ecbplus/10', '45/45ecbplus/11', '45/45ecbplus/12', '45/45ecbplus/2', '45/45ecbplus/3', '45/45ecbplus/4', '45/45ecbplus/5', '45/45ecbplus/6', '45/45ecbplus/7', '45/45ecbplus/8', '45/45ecbplus/9', '5/5ecb/1', '5/5ecb/10', '5/5ecb/11', '5/5ecb/12', '5/5ecb/13', '5/5ecb/14', '5/5ecb/2', '5/5ecb/3', '5/5ecb/4', '5/5ecb/5', '5/5ecb/6', '5/5ecb/7', '5/5ecb/9', '5/5ecbplus/1', '5/5ecbplus/10', '5/5ecbplus/2', '5/5ecbplus/3', '5/5ecbplus/4', '5/5ecbplus/5', '5/5ecbplus/6', '5/5ecbplus/7', '5/5ecbplus/8', '5/5ecbplus/9'])

In [5]:
cdcr_test.sentences['12/12ecb/15'][0]

{0: 'MSNBC',
 1: 'is',
 2: 'reporting',
 3: 'that',
 4: 'the',
 5: 'Indian',
 6: 'Navy',
 7: 'claims',
 8: 'they',
 9: 'have',
 10: 'captured',
 11: '23',
 12: 'pirates',
 13: 'in',
 14: 'the',
 15: 'Gulf',
 16: 'of',
 17: 'Aden',
 18: '.'}

In [7]:
cdcr_test.mentions[0].sent_id

0

In [8]:
cdcr_test.mentions[0].doc_id

'10'

In [6]:
import random

In [7]:
valrdm = random.randint(1,1000)
cdcr_test.mentions[valrdm].tokens_str

NameError: name 'cdcr_test' is not defined

In [38]:
valrdm

669

In [39]:
cdcr_test.mentions[valrdm].conll_doc_key

'21/21ecb/3'

In [43]:
cdcr_test.mentions[valrdm].tokens_str

'a store'

In [41]:
cdcr_test.sentences['21/21ecb/3'][cdcr_test.mentions[valrdm].sent_id]

{0: 'The',
 1: 'Hennepin',
 2: 'County',
 3: 'Attorney',
 4: 'filed',
 5: 'criminal',
 6: 'charges',
 7: 'Friday',
 8: 'against',
 9: 'the',
 10: 'man',
 11: 'who',
 12: 'they',
 13: 'say',
 14: 'hit',
 15: 'and',
 16: 'killed',
 17: 'a',
 18: 'woman',
 19: 'walking',
 20: 'out',
 21: 'of',
 22: 'a',
 23: 'store',
 24: '.'}

In [18]:
cdcr_test.mentions[0].tokens_str

'pirates'

In [13]:
cdcr_test.sentences[cdcr_test.mentions[0].conll_doc_key][0]

{0: 'The',
 1: 'Indian',
 2: 'navy',
 3: 'has',
 4: 'captured',
 5: '23',
 6: 'Somalian',
 7: 'pirates',
 8: '.'}

In [20]:
cdcr_test.mentions[0].conll_doc_key in cdcr_test.sentences.keys()

True

In [17]:
the_key = cdcr_test.mentions[100].conll_doc_key
the_sentence= cdcr_test.mentions[100].sent_id

cdcr_test.sentences[the_key][the_sentence]

[(0, 'In'),
 (1, 'another'),
 (2, 'successful'),
 (3, 'anti-piracy'),
 (4, 'operation'),
 (5, ','),
 (6, 'Navy'),
 (7, 'warship'),
 (8, 'on'),
 (9, 'Saturday'),
 (10, 'repulsed'),
 (11, 'an'),
 (12, 'attack'),
 (13, 'on'),
 (14, 'a'),
 (15, 'merchant'),
 (16, 'vessel'),
 (17, 'in'),
 (18, 'the'),
 (19, 'Gulf'),
 (20, 'of'),
 (21, 'Aden'),
 (22, 'and'),
 (23, 'nabbed'),
 (24, '23'),
 (25, 'Somali'),
 (26, 'and'),
 (27, 'Yemeni'),
 (28, 'sea'),
 (29, 'brigands'),
 (30, ','),
 (31, 'in'),
 (32, 'a'),
 (33, 'show'),
 (34, 'of'),
 (35, 'resolve'),
 (36, 'to'),
 (37, 'weed'),
 (38, 'out'),
 (39, 'the'),
 (40, 'menace'),
 (41, 'that'),
 (42, 'affected'),
 (43, 'maritime'),
 (44, 'trade'),
 (45, 'in'),
 (46, 'the'),
 (47, 'region'),
 (48, '.'),
 (0, 'In'),
 (1, 'another'),
 (2, 'successful'),
 (3, 'anti-piracy'),
 (4, 'operation'),
 (5, ','),
 (6, 'Navy'),
 (7, 'warship'),
 (8, 'on'),
 (9, 'Saturday'),
 (10, 'repulsed'),
 (11, 'an'),
 (12, 'attack'),
 (13, 'on'),
 (14, 'a'),
 (15, 'merchant'),
 (16, 'vessel'),
 (17, 'in'),
 (18, 'the'),
 (19, 'Gulf'),
 (20, 'of'),
 (21, 'Aden'),
 (22, 'and'),
 (23, 'nabbed'),
 (24, '23'),
 (25, 'Somali'),
 (26, 'and'),
 (27, 'Yemeni'),
 (28, 'sea'),
 (29, 'brigands'),
 (30, ','),
 (31, 'in'),
 (32, 'a'),
 (33, 'show'),
 (34, 'of'),
 (35, 'resolve'),
 (36, 'to'),
 (37, 'weed'),
 (38, 'out'),
 (39, 'the'),
 (40, 'menace'),
 (41, 'that'),
 (42, 'affected'),
 (43, 'maritime'),
 (44, 'trade'),
 (45, 'in'),
 (46, 'the'),
 (47, 'region'),
 (48, '.')]

In [11]:
cdcr_test.mentions[100].sent_id

0

In [9]:
cdcr_test.mentions[100].tokens_text

['affected']

In [2]:
def get_sentences_by_split(dataset_folder, split_name):
    docs_path = os.path.join(dataset_folder + split_name + '/', 'dataset.conll')
    documents, _ = read_conll_file(docs_path)
    sentences_dict = make_dict_of_sentences_no_cross(documents)

    return documents, sentences_dict

In [3]:
#ECB+:
common_data_folder = "../CDCR/data/"
dataset_name = 'ECBplus-prep'
dataset_folder = f"{common_data_folder}{dataset_name}/output_data/"
split_name = 'train'
ecbplus_documents_train, ecbplus_sentences_train = get_sentences_by_split(dataset_folder, split_name)

split_name = 'test'
ecbplus_documents_test,ecbplus_sentences_test = get_sentences_by_split(dataset_folder, split_name)

split_name = 'val'
ecbplus_documents_val ,ecbplus_sentences_val = get_sentences_by_split(dataset_folder, split_name)

# ecbplus_sentences = ecbplus_sentences_train + ecbplus_sentences_test + ecbplus_sentences_val

In [4]:
ecbplus_sentences_val['12/12ecb/1'][1]

[(0, 'Responding'),
 (1, 'to'),
 (2, 'a'),
 (3, 'distress'),
 (4, 'call'),
 (5, 'by'),
 (6, 'MV'),
 (7, 'Gibe'),
 (8, ','),
 (9, 'INS'),
 (10, 'Mysore'),
 (11, 'on'),
 (12, 'anti-piracy'),
 (13, 'patrol'),
 (14, 'in'),
 (15, 'the'),
 (16, 'area'),
 (17, ','),
 (18, 'swung'),
 (19, 'into'),
 (20, 'action'),
 (21, 'against'),
 (22, 'the'),
 (23, 'pirates'),
 (24, 'in'),
 (25, 'two'),
 (26, 'boats'),
 (27, ','),
 (28, 'a'),
 (29, 'Defence'),
 (30, 'Ministry'),
 (31, 'release'),
 (32, 'said'),
 (33, '.'),
 (0, 'Responding'),
 (1, 'to'),
 (2, 'a'),
 (3, 'distress'),
 (4, 'call'),
 (5, 'by'),
 (6, 'MV'),
 (7, 'Gibe'),
 (8, ','),
 (9, 'INS'),
 (10, 'Mysore'),
 (11, 'on'),
 (12, 'anti-piracy'),
 (13, 'patrol'),
 (14, 'in'),
 (15, 'the'),
 (16, 'area'),
 (17, ','),
 (18, 'swung'),
 (19, 'into'),
 (20, 'action'),
 (21, 'against'),
 (22, 'the'),
 (23, 'pirates'),
 (24, 'in'),
 (25, 'two'),
 (26, 'boats'),
 (27, ','),
 (28, 'a'),
 (29, 'Defence'),
 (30, 'Ministry'),
 (31, 'release'),
 (32, 'said'),
 (33, '.')]

In [5]:
dat = dataset_folder + split_name + "/entity_mentions.json"

In [6]:
dat

'../CDCR/data/ECBplus-prep/output_data/val/entity_mentions.json'

In [15]:
dat

'../CDCR/data/ECBplus-prep/output_data/val/entity_mentions.json'

In [7]:
import json
## Load mentions:
with open(dat, 'r') as f:
    mentions = json.load(f)

In [8]:
mentions[0]["coref_chain"]

'HUM17403498594960941'

In [9]:
new_mention = Mention(mentions[0])

In [13]:
new_mention.create_context(["asd","asa"],"new")

In [14]:
new_mention.new_context

['asd', 'asa']

In [8]:
for k,v in mentions[0].items():
    print(k,type(v))

coref_chain <class 'str'>
mention_ner <class 'str'>
mention_head_pos <class 'str'>
mention_head_lemma <class 'str'>
mention_head <class 'str'>
mention_head_id <class 'int'>
doc_id <class 'str'>
doc <class 'str'>
is_continuous <class 'bool'>
is_singleton <class 'bool'>
mention_id <class 'str'>
mention_type <class 'str'>
mention_full_type <class 'str'>
score <class 'float'>
sent_id <class 'int'>
mention_context <class 'list'>
tokens_number_context <class 'list'>
tokens_number <class 'list'>
tokens_str <class 'str'>
tokens_text <class 'list'>
topic_id <class 'str'>
topic <class 'str'>
subtopic_id <class 'str'>
subtopic <class 'str'>
coref_type <class 'str'>
description <class 'str'>
conll_doc_key <class 'str'>

In [ ]:
["coref_chain","doc_id","doc","mention_id","mention_context",'tokens_number',"tokens_str","tokens_text","topic_id","topic","subtopic_id","subtopic"]

In [15]:
mentions[0]

{'coref_chain': 'HUM17403498594960941',
 'mention_ner': 'O',
 'mention_head_pos': 'NOUN',
 'mention_head_lemma': 'pirate',
 'mention_head': 'pirates',
 'mention_head_id': 7,
 'doc_id': '10',
 'doc': '12_10ecb',
 'is_continuous': True,
 'is_singleton': False,
 'mention_id': '12_10ecb_HUM17403498594960941_0_7_dZMa',
 'mention_type': 'HUM',
 'mention_full_type': 'HUMAN_PART_PER',
 'score': -1.0,
 'sent_id': 0,
 'mention_context': ['The',
  'Indian',
  'navy',
  'has',
  'captured',
  '23',
  'Somalian',
  'pirates',
  '.',
  'The',
  'pirates',
  'were',
  'about',
  'to',
  'board',
  'a',
  'vessel',
  'in',
  'the',
  'Gulf',
  'of',
  'Aden',
  'when',
  'they',
  'were',
  'apprehended',
  '.',
  'Last',
  'month',
  ',',
  'India',
  "'s",
  'navy',
  'drew',
  'criticism',
  'after',
  'sinking',
  'a',
  'Thai',
  'fishing',
  'trawler',
  'that',
  'had',
  'been',
  'commandeered',
  'hours',
  'earlier',
  'by',
  'pirates',
  ',',
  'but',
  'the',
  'navy',
  'says',
  'it',
  'fired',
  'in',
  'self-defence',
  '.',
  'Somali',
  'pirates',
  'have',
  'become',
  'increasingly',
  'brazen',
  ',',
  'and',
  'recently',
  'seized',
  'a',
  'Saudi',
  'supertanker',
  'loaded',
  'with',
  'e75m',
  'worth',
  'of',
  'crude',
  'oil',
  '.'],
 'tokens_number_context': [7],
 'tokens_number': [7],
 'tokens_str': 'pirates',
 'tokens_text': ['pirates'],
 'topic_id': '12',
 'topic': '12',
 'subtopic_id': '12ecb',
 'subtopic': 'Indian Navy prevents a pirate attack on an Ethiopian vessel Gulf of Aden 2008',
 'coref_type': 'IDENTITY',
 'description': 't12b_pirates',
 'conll_doc_key': '12/12ecb/10'}

In [ ]:
'coref_chain', 'mention_ner', 'mention_head_pos', 'mention_head_lemma', 'mention_head', 'mention_head_id', 'doc_id', 
'doc', 'is_continuous', 'is_singleton', 'mention_id', 'mention_type', 'mention_full_type', 'score', 'sent_id', 'mention_context', 
'tokens_number_context', 'tokens_number', 'tokens_str', 'tokens_text', 'topic_id', 'topic', 'subtopic_id', 'subtopic', 'coref_type', 
'description', 'conll_doc_key'